ALTER TABLE ADUBOS_QUELATADOS ADD COLUMN IF NOT EXISTS DENSIDADE_G_ML DOUBLE PRECISION;
ALTER TABLE ADUBOS_QUELATADOS ADD COLUMN IF NOT EXISTS CONCENTRACAO_VOLUME_G_L DOUBLE PRECISION;
ALTER TABLE ADUBOS_QUELATADOS ADD COLUMN IF NOT EXISTS CONCENTRACAO_MASSA_G_KG DOUBLE PRECISION;
