CREATE TABLE IF NOT EXISTS ADUBOS_MINERAIS_SIMPLES_FOTOS (
    ADUBO_ID BIGINT NOT NULL,
    ORDEM INTEGER NOT NULL,
    ID_FOTO VARCHAR(255) NOT NULL,
    PRIMARY KEY (ADUBO_ID, ORDEM)
);

CREATE TABLE IF NOT EXISTS ADUBOS_MINERAIS_FORMULADOS_FOTOS (
    ADUBO_ID BIGINT NOT NULL,
    ORDEM INTEGER NOT NULL,
    ID_FOTO VARCHAR(255) NOT NULL,
    PRIMARY KEY (ADUBO_ID, ORDEM)
);

CREATE TABLE IF NOT EXISTS ADUBOS_ORGANO_MINERAIS_FOTOS (
    ADUBO_ID BIGINT NOT NULL,
    ORDEM INTEGER NOT NULL,
    ID_FOTO VARCHAR(255) NOT NULL,
    PRIMARY KEY (ADUBO_ID, ORDEM)
);

CREATE TABLE IF NOT EXISTS ADUBOS_ORGANICOS_FOTOS (
    ADUBO_ID BIGINT NOT NULL,
    ORDEM INTEGER NOT NULL,
    ID_FOTO VARCHAR(255) NOT NULL,
    PRIMARY KEY (ADUBO_ID, ORDEM)
);

CREATE TABLE IF NOT EXISTS ADUBOS_VERDES_FOTOS (
    ADUBO_ID BIGINT NOT NULL,
    ORDEM INTEGER NOT NULL,
    ID_FOTO VARCHAR(255) NOT NULL,
    PRIMARY KEY (ADUBO_ID, ORDEM)
);

CREATE TABLE IF NOT EXISTS ADUBOS_MINERAIS_FOTOS (
    ADUBO_ID BIGINT NOT NULL,
    ORDEM INTEGER NOT NULL,
    ID_FOTO VARCHAR(255) NOT NULL,
    PRIMARY KEY (ADUBO_ID, ORDEM)
);

CREATE TABLE IF NOT EXISTS ADUBOS_QUELATADOS_FOTOS (
    ADUBO_ID BIGINT NOT NULL,
    ORDEM INTEGER NOT NULL,
    ID_FOTO VARCHAR(255) NOT NULL,
    PRIMARY KEY (ADUBO_ID, ORDEM)
);

CREATE TABLE IF NOT EXISTS BIO_FERTILIZANTES_FOTOS (
    ADUBO_ID BIGINT NOT NULL,
    ORDEM INTEGER NOT NULL,
    ID_FOTO VARCHAR(255) NOT NULL,
    PRIMARY KEY (ADUBO_ID, ORDEM)
);
