ALTER TABLE ADUBOS_MINERAIS_SIMPLES ADD COLUMN IF NOT EXISTS DATA_TOMADA_PRECO DATE;
ALTER TABLE ADUBOS_MINERAIS_SIMPLES ADD COLUMN IF NOT EXISTS PRECO_SACO_5KG NUMERIC(19, 2);
ALTER TABLE ADUBOS_MINERAIS_SIMPLES ADD COLUMN IF NOT EXISTS PRECO_SACO_25KG NUMERIC(19, 2);
ALTER TABLE ADUBOS_MINERAIS_SIMPLES ADD COLUMN IF NOT EXISTS PRECO_SACO_50KG NUMERIC(19, 2);
ALTER TABLE ADUBOS_MINERAIS_SIMPLES ADD COLUMN IF NOT EXISTS PRECO_SACO_1000KG NUMERIC(19, 2);

ALTER TABLE ADUBOS_MINERAIS_FORMULADOS ADD COLUMN IF NOT EXISTS DATA_TOMADA_PRECO DATE;
ALTER TABLE ADUBOS_MINERAIS_FORMULADOS ADD COLUMN IF NOT EXISTS PRECO_SACO_5KG NUMERIC(19, 2);
ALTER TABLE ADUBOS_MINERAIS_FORMULADOS ADD COLUMN IF NOT EXISTS PRECO_SACO_25KG NUMERIC(19, 2);
ALTER TABLE ADUBOS_MINERAIS_FORMULADOS ADD COLUMN IF NOT EXISTS PRECO_SACO_50KG NUMERIC(19, 2);
ALTER TABLE ADUBOS_MINERAIS_FORMULADOS ADD COLUMN IF NOT EXISTS PRECO_SACO_1000KG NUMERIC(19, 2);

ALTER TABLE ADUBOS_ORGANO_MINERAIS ADD COLUMN IF NOT EXISTS DATA_TOMADA_PRECO DATE;
ALTER TABLE ADUBOS_ORGANO_MINERAIS ADD COLUMN IF NOT EXISTS PRECO_SACO_5KG NUMERIC(19, 2);
ALTER TABLE ADUBOS_ORGANO_MINERAIS ADD COLUMN IF NOT EXISTS PRECO_SACO_25KG NUMERIC(19, 2);
ALTER TABLE ADUBOS_ORGANO_MINERAIS ADD COLUMN IF NOT EXISTS PRECO_SACO_50KG NUMERIC(19, 2);
ALTER TABLE ADUBOS_ORGANO_MINERAIS ADD COLUMN IF NOT EXISTS PRECO_SACO_1000KG NUMERIC(19, 2);

ALTER TABLE ADUBOS_VERDES ADD COLUMN IF NOT EXISTS DATA_TOMADA_PRECO DATE;
ALTER TABLE ADUBOS_VERDES ADD COLUMN IF NOT EXISTS PRECO_SACO_5KG NUMERIC(19, 2);
ALTER TABLE ADUBOS_VERDES ADD COLUMN IF NOT EXISTS PRECO_SACO_25KG NUMERIC(19, 2);
ALTER TABLE ADUBOS_VERDES ADD COLUMN IF NOT EXISTS PRECO_SACO_50KG NUMERIC(19, 2);
ALTER TABLE ADUBOS_VERDES ADD COLUMN IF NOT EXISTS PRECO_SACO_1000KG NUMERIC(19, 2);

ALTER TABLE ADUBOS_ORGANICOS ADD COLUMN IF NOT EXISTS DATA_TOMADA_PRECO DATE;
ALTER TABLE ADUBOS_ORGANICOS ADD COLUMN IF NOT EXISTS PRECO_SACO_5KG NUMERIC(19, 2);
ALTER TABLE ADUBOS_ORGANICOS ADD COLUMN IF NOT EXISTS PRECO_SACO_25KG NUMERIC(19, 2);
ALTER TABLE ADUBOS_ORGANICOS ADD COLUMN IF NOT EXISTS PRECO_SACO_50KG NUMERIC(19, 2);
ALTER TABLE ADUBOS_ORGANICOS ADD COLUMN IF NOT EXISTS PRECO_SACO_1000KG NUMERIC(19, 2);

ALTER TABLE ADUBOS_MINERAIS ADD COLUMN IF NOT EXISTS DATA_TOMADA_PRECO DATE;
ALTER TABLE ADUBOS_MINERAIS ADD COLUMN IF NOT EXISTS PRECO_SACO_5KG NUMERIC(19, 2);
ALTER TABLE ADUBOS_MINERAIS ADD COLUMN IF NOT EXISTS PRECO_SACO_25KG NUMERIC(19, 2);
ALTER TABLE ADUBOS_MINERAIS ADD COLUMN IF NOT EXISTS PRECO_SACO_50KG NUMERIC(19, 2);
ALTER TABLE ADUBOS_MINERAIS ADD COLUMN IF NOT EXISTS PRECO_SACO_1000KG NUMERIC(19, 2);

ALTER TABLE ADUBOS_QUELATADOS ADD COLUMN IF NOT EXISTS DATA_TOMADA_PRECO DATE;
ALTER TABLE ADUBOS_QUELATADOS ADD COLUMN IF NOT EXISTS PRECO_SACO_5KG NUMERIC(19, 2);
ALTER TABLE ADUBOS_QUELATADOS ADD COLUMN IF NOT EXISTS PRECO_SACO_25KG NUMERIC(19, 2);
ALTER TABLE ADUBOS_QUELATADOS ADD COLUMN IF NOT EXISTS PRECO_SACO_50KG NUMERIC(19, 2);
ALTER TABLE ADUBOS_QUELATADOS ADD COLUMN IF NOT EXISTS PRECO_SACO_1000KG NUMERIC(19, 2);

ALTER TABLE BIO_FERTILIZANTES ADD COLUMN IF NOT EXISTS DATA_TOMADA_PRECO DATE;
ALTER TABLE BIO_FERTILIZANTES ADD COLUMN IF NOT EXISTS PRECO_SACO_5KG NUMERIC(19, 2);
ALTER TABLE BIO_FERTILIZANTES ADD COLUMN IF NOT EXISTS PRECO_SACO_25KG NUMERIC(19, 2);
ALTER TABLE BIO_FERTILIZANTES ADD COLUMN IF NOT EXISTS PRECO_SACO_50KG NUMERIC(19, 2);
ALTER TABLE BIO_FERTILIZANTES ADD COLUMN IF NOT EXISTS PRECO_SACO_1000KG NUMERIC(19, 2);
