ALTER TABLE TABELAS_ADUBACAO_CULTURAS
    ADD COLUMN IF NOT EXISTS VALOR_MAXIMO_ESPACAMENTO_USADO DOUBLE PRECISION;

UPDATE TABELAS_ADUBACAO_CULTURAS
SET VALOR_MAXIMO_ESPACAMENTO_USADO = VALOR_ESPACAMENTO_USADO
WHERE VALOR_MAXIMO_ESPACAMENTO_USADO IS NULL;
