-- Potassio em Teores de Nutrientes Diversos: quatro limites independentes,
-- compativeis com o classificador Baixo/Medio/Alto.
ALTER TABLE FAIXAS_DE_TEORES_DIVERSOS
    ADD COLUMN IF NOT EXISTS TEOR_FINAL_BAIXO_POTASSIO DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS TEOR_INICIAL_MEDIO_POTASSIO DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS TEOR_FINAL_MEDIO_POTASSIO DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS TEOR_INICIAL_ALTO_POTASSIO DOUBLE PRECISION;

-- Restaura somente limites semanticamente identicos preservados pela migration
-- V20260703_06; instalacoes sem valores anteriores permanecem com valores nulos.
UPDATE FAIXAS_DE_TEORES_DIVERSOS
SET TEOR_FINAL_BAIXO_POTASSIO = COALESCE(TEOR_FINAL_BAIXO_POTASSIO, LEGACY_TEOR_FINAL_BAIXO_POTASSIO),
    TEOR_INICIAL_MEDIO_POTASSIO = COALESCE(TEOR_INICIAL_MEDIO_POTASSIO, LEGACY_TEOR_INICIAL_MEDIO_POTASSIO),
    TEOR_FINAL_MEDIO_POTASSIO = COALESCE(TEOR_FINAL_MEDIO_POTASSIO, LEGACY_TEOR_FINAL_MEDIO_POTASSIO),
    TEOR_INICIAL_ALTO_POTASSIO = COALESCE(TEOR_INICIAL_ALTO_POTASSIO, LEGACY_TEOR_INICIAL_ALTO_POTASSIO);
