DO $$
BEGIN
    IF EXISTS (
        SELECT 1
        FROM information_schema.columns
        WHERE table_name = 'adubos_organicos'
          AND column_name = 'porcentagem_cinzas'
    ) AND NOT EXISTS (
        SELECT 1
        FROM information_schema.columns
        WHERE table_name = 'adubos_organicos'
          AND column_name = 'porcentagem_materia_organica'
    ) THEN
        ALTER TABLE ADUBOS_ORGANICOS RENAME COLUMN PORCENTAGEM_CINZAS TO PORCENTAGEM_MATERIA_ORGANICA;
    END IF;
END $$;

ALTER TABLE ADUBOS_ORGANICOS ADD COLUMN IF NOT EXISTS PORCENTAGEM_MATERIA_ORGANICA DOUBLE PRECISION;

DO $$
BEGIN
    IF EXISTS (
        SELECT 1
        FROM information_schema.columns
        WHERE table_name = 'adubos_organicos'
          AND column_name = 'porcentagem_cinzas'
    ) THEN
        UPDATE ADUBOS_ORGANICOS
        SET PORCENTAGEM_MATERIA_ORGANICA = PORCENTAGEM_CINZAS
        WHERE PORCENTAGEM_MATERIA_ORGANICA IS NULL
          AND PORCENTAGEM_CINZAS IS NOT NULL;
    END IF;
END $$;

ALTER TABLE ADUBOS_ORGANICOS ADD COLUMN IF NOT EXISTS TAXA_MINERALIZACAO_PRIMEIRO_ANO_PERCENTUAL DOUBLE PRECISION;
ALTER TABLE ADUBOS_ORGANICOS ADD COLUMN IF NOT EXISTS TAXA_MINERALIZACAO_SEGUNDO_ANO_PERCENTUAL DOUBLE PRECISION;
ALTER TABLE ADUBOS_ORGANICOS ADD COLUMN IF NOT EXISTS TAXA_MINERALIZACAO_TERCEIRO_ANO_PERCENTUAL DOUBLE PRECISION;
