ALTER TABLE ADUBOS_MINERAIS_SIMPLES ADD COLUMN IF NOT EXISTS PUBLICO BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE ADUBOS_MINERAIS_FORMULADOS ADD COLUMN IF NOT EXISTS PUBLICO BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE ADUBOS_ORGANO_MINERAIS ADD COLUMN IF NOT EXISTS PUBLICO BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE ADUBOS_VERDES ADD COLUMN IF NOT EXISTS PUBLICO BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE ADUBOS_MINERAIS ADD COLUMN IF NOT EXISTS PUBLICO BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE ADUBOS_QUELATADOS ADD COLUMN IF NOT EXISTS PUBLICO BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE BIO_FERTILIZANTES ADD COLUMN IF NOT EXISTS PUBLICO BOOLEAN NOT NULL DEFAULT FALSE;

CREATE INDEX IF NOT EXISTS IDX_ADUBOS_MINERAIS_SIMPLES_PUBLICO ON ADUBOS_MINERAIS_SIMPLES (PUBLICO);
CREATE INDEX IF NOT EXISTS IDX_ADUBOS_MINERAIS_FORMULADOS_PUBLICO ON ADUBOS_MINERAIS_FORMULADOS (PUBLICO);
CREATE INDEX IF NOT EXISTS IDX_ADUBOS_ORGANO_MINERAIS_PUBLICO ON ADUBOS_ORGANO_MINERAIS (PUBLICO);
CREATE INDEX IF NOT EXISTS IDX_ADUBOS_VERDES_PUBLICO ON ADUBOS_VERDES (PUBLICO);
CREATE INDEX IF NOT EXISTS IDX_ADUBOS_MINERAIS_PUBLICO ON ADUBOS_MINERAIS (PUBLICO);
CREATE INDEX IF NOT EXISTS IDX_ADUBOS_QUELATADOS_PUBLICO ON ADUBOS_QUELATADOS (PUBLICO);
CREATE INDEX IF NOT EXISTS IDX_BIO_FERTILIZANTES_PUBLICO ON BIO_FERTILIZANTES (PUBLICO);
