ALTER TABLE RECOMENDACOES
    ADD COLUMN REPORT_CLIENT_PRODUCER VARCHAR(255),
    ADD COLUMN REPORT_PROPERTY_NAME VARCHAR(255),
    ADD COLUMN REPORT_MUNICIPALITY VARCHAR(120),
    ADD COLUMN REPORT_STATE VARCHAR(2),
    ADD COLUMN REPORT_PLOT_IDENTIFICATION VARCHAR(255),
    ADD COLUMN REPORT_EVALUATED_AREA_HA DOUBLE PRECISION,
    ADD COLUMN REPORT_TECHNICAL_RESPONSIBLE VARCHAR(255),
    ADD COLUMN REPORT_PROFESSIONAL_REGISTRATION VARCHAR(120),
    ADD COLUMN REPORT_RESPONSIBLE_PHONE VARCHAR(80),
    ADD COLUMN REPORT_RESPONSIBLE_EMAIL VARCHAR(255),
    ADD COLUMN REPORT_ISSUE_DATE DATE,
    ADD COLUMN REPORT_SIGNATURE_AUTHOR VARCHAR(255);
