ALTER TABLE PROPRIEDADES ADD COLUMN IF NOT EXISTS ID_FOTO VARCHAR(255);
ALTER TABLE TALHOES ADD COLUMN IF NOT EXISTS ID_FOTO VARCHAR(255);
ALTER TABLE CULTURAS ADD COLUMN IF NOT EXISTS ID_FOTO VARCHAR(255);
