CREATE TABLE IF NOT EXISTS ADUBACAO_CORRETIVA_DE_P2O5 (
    id BIGSERIAL PRIMARY KEY,
    ID_TABELA BIGINT NOT NULL,
    ARGILA_MINIMA DOUBLE PRECISION,
    ARGILA_MAXIMA DOUBLE PRECISION,
    P_MEHLICH_MINIMO DOUBLE PRECISION,
    P_MEHLICH_MAXIMO DOUBLE PRECISION,
    DOSE_P2O5 DOUBLE PRECISION NOT NULL,
    OBSERVACOES VARCHAR(1000),
    FONTES VARCHAR(1000),
    CONSTRAINT FK_ADUBACAO_CORRETIVA_P2O5_TABELA FOREIGN KEY (ID_TABELA)
        REFERENCES TABELAS_DE_CRITERIOS_DE_INTERPRETACAO_DA_FERTILIDADE_DO_SOLO(id)
);

CREATE INDEX IF NOT EXISTS IDX_ADUBACAO_CORRETIVA_P2O5_TABELA
    ON ADUBACAO_CORRETIVA_DE_P2O5 (ID_TABELA);

CREATE TABLE IF NOT EXISTS ADUBACAO_CORRETIVA_DE_K2O (
    id BIGSERIAL PRIMARY KEY,
    ID_TABELA BIGINT NOT NULL,
    CTC_MINIMA DOUBLE PRECISION,
    CTC_MAXIMA DOUBLE PRECISION,
    K_MINIMO DOUBLE PRECISION,
    K_MAXIMO DOUBLE PRECISION,
    DOSE_K2O DOUBLE PRECISION NOT NULL,
    OBSERVACOES VARCHAR(1000),
    FONTES VARCHAR(1000),
    CONSTRAINT FK_ADUBACAO_CORRETIVA_K2O_TABELA FOREIGN KEY (ID_TABELA)
        REFERENCES TABELAS_DE_CRITERIOS_DE_INTERPRETACAO_DA_FERTILIDADE_DO_SOLO(id)
);

CREATE INDEX IF NOT EXISTS IDX_ADUBACAO_CORRETIVA_K2O_TABELA
    ON ADUBACAO_CORRETIVA_DE_K2O (ID_TABELA);
