ALTER TABLE IF EXISTS faixas_de_teores_diversos
    ADD COLUMN IF NOT EXISTS menor_valor_ph_cacl2 DOUBLE PRECISION NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS valor_inicial_baixo_ph_cacl2 DOUBLE PRECISION NOT NULL DEFAULT 5,
    ADD COLUMN IF NOT EXISTS valor_final_baixo_ph_cacl2 DOUBLE PRECISION NOT NULL DEFAULT 10,
    ADD COLUMN IF NOT EXISTS valor_inicial_medio_ph_cacl2 DOUBLE PRECISION NOT NULL DEFAULT 10,
    ADD COLUMN IF NOT EXISTS valor_final_medio_ph_cacl2 DOUBLE PRECISION NOT NULL DEFAULT 20,
    ADD COLUMN IF NOT EXISTS valor_inicial_alto_ph_cacl2 DOUBLE PRECISION NOT NULL DEFAULT 20,
    ADD COLUMN IF NOT EXISTS valor_final_alto_ph_cacl2 DOUBLE PRECISION NOT NULL DEFAULT 999,
    ADD COLUMN IF NOT EXISTS maior_valor_ph_cacl2 DOUBLE PRECISION NOT NULL DEFAULT 999;
