ALTER TABLE CULTURAS
    ADD COLUMN IF NOT EXISTS MODO_ESPACAMENTO VARCHAR(40) DEFAULT 'PLANTS_PER_LINEAR_METER',
    ADD COLUMN IF NOT EXISTS DISTANCIA_ENTRE_COVAS DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS N_PLANTAS_POR_COVA DOUBLE PRECISION;

UPDATE CULTURAS
SET MODO_ESPACAMENTO = 'PLANTS_PER_LINEAR_METER'
WHERE MODO_ESPACAMENTO IS NULL;
