ALTER TABLE IF EXISTS ADUBOS_MINERAIS
    ADD COLUMN IF NOT EXISTS NATUREZA_FISICA VARCHAR(20) NOT NULL DEFAULT 'SOLIDO',
    ADD COLUMN IF NOT EXISTS DENSIDADE_G_ML DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS CONCENTRACAO_VOLUME_G_L DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS CONCENTRACAO_MASSA_G_KG DOUBLE PRECISION;

ALTER TABLE IF EXISTS ADUBOS_QUELATADOS
    ADD COLUMN IF NOT EXISTS DENSIDADE_G_ML DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS CONCENTRACAO_VOLUME_G_L DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS CONCENTRACAO_MASSA_G_KG DOUBLE PRECISION;

ALTER TABLE IF EXISTS BIO_FERTILIZANTES
    ADD COLUMN IF NOT EXISTS DENSIDADE_G_ML DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS CONCENTRACAO_VOLUME_G_L DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS CONCENTRACAO_MASSA_G_KG DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS PROTEINAS_G_L DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS AMINOACIDOS_G_L DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS AMIDOS_G_L DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS ACUCARES_G_L DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS COMPOSTOS_DIVERSOS_G_L DOUBLE PRECISION;
