ALTER TABLE TABELAS_ADUBACAO_CULTURAS
    ADD COLUMN IF NOT EXISTS FONTES VARCHAR(255);

ALTER TABLE TABELAS_ADUBACAO_CULTURAS
    ALTER COLUMN OBSERVACOES DROP NOT NULL;

ALTER TABLE TABELAS_DE_INTERPRETACAO_DE_ANÁLISE_FOLIAR_DE_CULTURAS
    ADD COLUMN IF NOT EXISTS OBSERVACOES VARCHAR(255);

ALTER TABLE TABELAS_DE_INTERPRETACAO_DE_ANÁLISE_FOLIAR_DE_CULTURAS
    ADD COLUMN IF NOT EXISTS FONTES VARCHAR(255);

ALTER TABLE TABELAS_DE_CRITERIOS_DE_INTERPRETACAO_DA_FERTILIDADE_DO_SOLO
    ADD COLUMN IF NOT EXISTS OBSERVACOES VARCHAR(255);

ALTER TABLE TABELAS_DE_CRITERIOS_DE_INTERPRETACAO_DA_FERTILIDADE_DO_SOLO
    ADD COLUMN IF NOT EXISTS FONTES VARCHAR(255);
