ALTER TABLE ADUBOS_MINERAIS ADD COLUMN IF NOT EXISTS NATUREZA_FISICA VARCHAR(20) NOT NULL DEFAULT 'SOLIDO';
ALTER TABLE ADUBOS_MINERAIS ADD COLUMN IF NOT EXISTS DENSIDADE_G_ML DOUBLE PRECISION;
ALTER TABLE ADUBOS_MINERAIS ADD COLUMN IF NOT EXISTS CONCENTRACAO_VOLUME_G_L DOUBLE PRECISION;
ALTER TABLE ADUBOS_MINERAIS ADD COLUMN IF NOT EXISTS CONCENTRACAO_MASSA_G_KG DOUBLE PRECISION;
