ALTER TABLE ADUBOS_VERDES ADD COLUMN IF NOT EXISTS PRODUTIVIDADE_ESPERADA_KG_HA DOUBLE PRECISION;
ALTER TABLE ADUBOS_VERDES ADD COLUMN IF NOT EXISTS TAXA_MINERALIZACAO_PRIMEIRO_ANO_PERCENTUAL DOUBLE PRECISION;
ALTER TABLE ADUBOS_VERDES ADD COLUMN IF NOT EXISTS TAXA_MINERALIZACAO_SEGUNDO_ANO_PERCENTUAL DOUBLE PRECISION;
ALTER TABLE ADUBOS_VERDES ADD COLUMN IF NOT EXISTS TAXA_MINERALIZACAO_TERCEIRO_ANO_PERCENTUAL DOUBLE PRECISION;
