ALTER TABLE ADUBOS_MINERAIS_SIMPLES ADD COLUMN IF NOT EXISTS PUBLICO BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE ADUBOS_MINERAIS_FORMULADOS ADD COLUMN IF NOT EXISTS PUBLICO BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE ADUBOS_ORGANO_MINERAIS ADD COLUMN IF NOT EXISTS PUBLICO BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE ADUBOS_ORGANICOS ADD COLUMN IF NOT EXISTS PUBLICO BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE ADUBOS_VERDES ADD COLUMN IF NOT EXISTS PUBLICO BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE ADUBOS_MINERAIS ADD COLUMN IF NOT EXISTS PUBLICO BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE ADUBOS_QUELATADOS ADD COLUMN IF NOT EXISTS PUBLICO BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE BIO_FERTILIZANTES ADD COLUMN IF NOT EXISTS PUBLICO BOOLEAN NOT NULL DEFAULT FALSE;

CREATE INDEX IF NOT EXISTS IDX_ADUBOS_ORGANICOS_PUBLICO ON ADUBOS_ORGANICOS (PUBLICO);
