-- Hardening defensivo das estruturas introduzidas nas rotinas agronomicas recentes.
-- As migrations V20260704_01..06 criam/removem a estrutura esperada; esta migration
-- cobre bancos que tenham recebido deploys parciais ou tabelas criadas manualmente.

ALTER TABLE IF EXISTS faixas_de_teores_diversos
    DROP COLUMN IF EXISTS menor_teor_potassio,
    DROP COLUMN IF EXISTS teor_inicial_baixo_potassio,
    DROP COLUMN IF EXISTS teor_final_baixo_potassio,
    DROP COLUMN IF EXISTS teor_inicial_medio_potassio,
    DROP COLUMN IF EXISTS teor_final_medio_potassio,
    DROP COLUMN IF EXISTS teor_inicial_alto_potassio,
    DROP COLUMN IF EXISTS teor_final_alto_potassio,
    DROP COLUMN IF EXISTS maior_teor_potassio;

DROP TABLE IF EXISTS teores_trocaveis_de_potassio;

ALTER TABLE IF EXISTS ADUBOS_MINERAIS_SIMPLES
    ADD COLUMN IF NOT EXISTS DATA_TOMADA_PRECO DATE,
    ADD COLUMN IF NOT EXISTS PRECO_SACO_5KG NUMERIC(19, 2),
    ADD COLUMN IF NOT EXISTS PRECO_SACO_25KG NUMERIC(19, 2),
    ADD COLUMN IF NOT EXISTS PRECO_SACO_50KG NUMERIC(19, 2),
    ADD COLUMN IF NOT EXISTS PRECO_SACO_1000KG NUMERIC(19, 2);

ALTER TABLE IF EXISTS ADUBOS_MINERAIS_FORMULADOS
    ADD COLUMN IF NOT EXISTS DATA_TOMADA_PRECO DATE,
    ADD COLUMN IF NOT EXISTS PRECO_SACO_5KG NUMERIC(19, 2),
    ADD COLUMN IF NOT EXISTS PRECO_SACO_25KG NUMERIC(19, 2),
    ADD COLUMN IF NOT EXISTS PRECO_SACO_50KG NUMERIC(19, 2),
    ADD COLUMN IF NOT EXISTS PRECO_SACO_1000KG NUMERIC(19, 2);

ALTER TABLE IF EXISTS ADUBOS_ORGANO_MINERAIS
    ADD COLUMN IF NOT EXISTS DATA_TOMADA_PRECO DATE,
    ADD COLUMN IF NOT EXISTS PRECO_SACO_5KG NUMERIC(19, 2),
    ADD COLUMN IF NOT EXISTS PRECO_SACO_25KG NUMERIC(19, 2),
    ADD COLUMN IF NOT EXISTS PRECO_SACO_50KG NUMERIC(19, 2),
    ADD COLUMN IF NOT EXISTS PRECO_SACO_1000KG NUMERIC(19, 2);

ALTER TABLE IF EXISTS ADUBOS_VERDES
    ADD COLUMN IF NOT EXISTS DATA_TOMADA_PRECO DATE,
    ADD COLUMN IF NOT EXISTS PRECO_SACO_5KG NUMERIC(19, 2),
    ADD COLUMN IF NOT EXISTS PRECO_SACO_25KG NUMERIC(19, 2),
    ADD COLUMN IF NOT EXISTS PRECO_SACO_50KG NUMERIC(19, 2),
    ADD COLUMN IF NOT EXISTS PRECO_SACO_1000KG NUMERIC(19, 2);

ALTER TABLE IF EXISTS ADUBOS_ORGANICOS
    ADD COLUMN IF NOT EXISTS DATA_TOMADA_PRECO DATE,
    ADD COLUMN IF NOT EXISTS PRECO_SACO_5KG NUMERIC(19, 2),
    ADD COLUMN IF NOT EXISTS PRECO_SACO_25KG NUMERIC(19, 2),
    ADD COLUMN IF NOT EXISTS PRECO_SACO_50KG NUMERIC(19, 2),
    ADD COLUMN IF NOT EXISTS PRECO_SACO_1000KG NUMERIC(19, 2);

ALTER TABLE IF EXISTS ADUBOS_MINERAIS
    ADD COLUMN IF NOT EXISTS DATA_TOMADA_PRECO DATE,
    ADD COLUMN IF NOT EXISTS PRECO_SACO_5KG NUMERIC(19, 2),
    ADD COLUMN IF NOT EXISTS PRECO_SACO_25KG NUMERIC(19, 2),
    ADD COLUMN IF NOT EXISTS PRECO_SACO_50KG NUMERIC(19, 2),
    ADD COLUMN IF NOT EXISTS PRECO_SACO_1000KG NUMERIC(19, 2);

ALTER TABLE IF EXISTS ADUBOS_QUELATADOS
    ADD COLUMN IF NOT EXISTS DATA_TOMADA_PRECO DATE,
    ADD COLUMN IF NOT EXISTS PRECO_SACO_5KG NUMERIC(19, 2),
    ADD COLUMN IF NOT EXISTS PRECO_SACO_25KG NUMERIC(19, 2),
    ADD COLUMN IF NOT EXISTS PRECO_SACO_50KG NUMERIC(19, 2),
    ADD COLUMN IF NOT EXISTS PRECO_SACO_1000KG NUMERIC(19, 2);

ALTER TABLE IF EXISTS BIO_FERTILIZANTES
    ADD COLUMN IF NOT EXISTS DATA_TOMADA_PRECO DATE,
    ADD COLUMN IF NOT EXISTS PRECO_SACO_5KG NUMERIC(19, 2),
    ADD COLUMN IF NOT EXISTS PRECO_SACO_25KG NUMERIC(19, 2),
    ADD COLUMN IF NOT EXISTS PRECO_SACO_50KG NUMERIC(19, 2),
    ADD COLUMN IF NOT EXISTS PRECO_SACO_1000KG NUMERIC(19, 2);

DO $$
DECLARE
    table_exists BOOLEAN;
    parent_exists BOOLEAN;
    null_count BIGINT;
    orphan_count BIGINT;
    duplicate_count BIGINT;
BEGIN
    parent_exists := to_regclass('public.tabelas_de_criterios_de_interpretacao_da_fertilidade_do_solo') IS NOT NULL;

    IF parent_exists AND to_regclass('public.teores_e_doses_de_k') IS NULL THEN
        CREATE TABLE TEORES_E_DOSES_DE_K (
            id BIGSERIAL PRIMARY KEY,
            ID_TABELA BIGINT NOT NULL,
            CTC_MENOR_40_TEOR_BAIXO_MENOR_QUE DOUBLE PRECISION NOT NULL,
            CTC_MENOR_40_DOSE_PARA_TEOR_BAIXO DOUBLE PRECISION NOT NULL,
            CTC_MENOR_40_MEDIO_MENOR_TEOR DOUBLE PRECISION NOT NULL,
            CTC_MENOR_40_MEDIO_MAIOR_TEOR DOUBLE PRECISION NOT NULL,
            CTC_MENOR_40_DOSE_PARA_TEOR_MEDIO DOUBLE PRECISION NOT NULL,
            CTC_MENOR_40_ADEQUADO_MENOR_TEOR DOUBLE PRECISION NOT NULL,
            CTC_MENOR_40_ADEQUADO_MAIOR_TEOR DOUBLE PRECISION NOT NULL,
            CTC_MENOR_40_DOSE_PARA_TEOR_ADEQUADO DOUBLE PRECISION NOT NULL,
            CTC_MENOR_40_TEOR_ALTO_MAIOR_QUE DOUBLE PRECISION NOT NULL,
            CTC_MENOR_40_DOSE_PARA_TEOR_ALTO DOUBLE PRECISION NOT NULL,
            CTC_MAIOR_IGUAL_40_TEOR_BAIXO_MENOR_QUE DOUBLE PRECISION NOT NULL,
            CTC_MAIOR_IGUAL_40_DOSE_PARA_TEOR_BAIXO DOUBLE PRECISION NOT NULL,
            CTC_MAIOR_IGUAL_40_MEDIO_MENOR_TEOR DOUBLE PRECISION NOT NULL,
            CTC_MAIOR_IGUAL_40_MEDIO_MAIOR_TEOR DOUBLE PRECISION NOT NULL,
            CTC_MAIOR_IGUAL_40_DOSE_PARA_TEOR_MEDIO DOUBLE PRECISION NOT NULL,
            CTC_MAIOR_IGUAL_40_ADEQUADO_MENOR_TEOR DOUBLE PRECISION NOT NULL,
            CTC_MAIOR_IGUAL_40_ADEQUADO_MAIOR_TEOR DOUBLE PRECISION NOT NULL,
            CTC_MAIOR_IGUAL_40_DOSE_PARA_TEOR_ADEQUADO DOUBLE PRECISION NOT NULL,
            CTC_MAIOR_IGUAL_40_TEOR_ALTO_MAIOR_QUE DOUBLE PRECISION NOT NULL,
            CTC_MAIOR_IGUAL_40_DOSE_PARA_TEOR_ALTO DOUBLE PRECISION NOT NULL,
            OBSERVACOES VARCHAR(1000),
            FONTES VARCHAR(1000)
        );
    END IF;

    table_exists := to_regclass('public.teores_e_doses_de_k') IS NOT NULL;
    IF table_exists THEN
        ALTER TABLE TEORES_E_DOSES_DE_K
            ADD COLUMN IF NOT EXISTS ID_TABELA BIGINT,
            ADD COLUMN IF NOT EXISTS CTC_MENOR_40_TEOR_BAIXO_MENOR_QUE DOUBLE PRECISION,
            ADD COLUMN IF NOT EXISTS CTC_MENOR_40_DOSE_PARA_TEOR_BAIXO DOUBLE PRECISION,
            ADD COLUMN IF NOT EXISTS CTC_MENOR_40_MEDIO_MENOR_TEOR DOUBLE PRECISION,
            ADD COLUMN IF NOT EXISTS CTC_MENOR_40_MEDIO_MAIOR_TEOR DOUBLE PRECISION,
            ADD COLUMN IF NOT EXISTS CTC_MENOR_40_DOSE_PARA_TEOR_MEDIO DOUBLE PRECISION,
            ADD COLUMN IF NOT EXISTS CTC_MENOR_40_ADEQUADO_MENOR_TEOR DOUBLE PRECISION,
            ADD COLUMN IF NOT EXISTS CTC_MENOR_40_ADEQUADO_MAIOR_TEOR DOUBLE PRECISION,
            ADD COLUMN IF NOT EXISTS CTC_MENOR_40_DOSE_PARA_TEOR_ADEQUADO DOUBLE PRECISION,
            ADD COLUMN IF NOT EXISTS CTC_MENOR_40_TEOR_ALTO_MAIOR_QUE DOUBLE PRECISION,
            ADD COLUMN IF NOT EXISTS CTC_MENOR_40_DOSE_PARA_TEOR_ALTO DOUBLE PRECISION,
            ADD COLUMN IF NOT EXISTS CTC_MAIOR_IGUAL_40_TEOR_BAIXO_MENOR_QUE DOUBLE PRECISION,
            ADD COLUMN IF NOT EXISTS CTC_MAIOR_IGUAL_40_DOSE_PARA_TEOR_BAIXO DOUBLE PRECISION,
            ADD COLUMN IF NOT EXISTS CTC_MAIOR_IGUAL_40_MEDIO_MENOR_TEOR DOUBLE PRECISION,
            ADD COLUMN IF NOT EXISTS CTC_MAIOR_IGUAL_40_MEDIO_MAIOR_TEOR DOUBLE PRECISION,
            ADD COLUMN IF NOT EXISTS CTC_MAIOR_IGUAL_40_DOSE_PARA_TEOR_MEDIO DOUBLE PRECISION,
            ADD COLUMN IF NOT EXISTS CTC_MAIOR_IGUAL_40_ADEQUADO_MENOR_TEOR DOUBLE PRECISION,
            ADD COLUMN IF NOT EXISTS CTC_MAIOR_IGUAL_40_ADEQUADO_MAIOR_TEOR DOUBLE PRECISION,
            ADD COLUMN IF NOT EXISTS CTC_MAIOR_IGUAL_40_DOSE_PARA_TEOR_ADEQUADO DOUBLE PRECISION,
            ADD COLUMN IF NOT EXISTS CTC_MAIOR_IGUAL_40_TEOR_ALTO_MAIOR_QUE DOUBLE PRECISION,
            ADD COLUMN IF NOT EXISTS CTC_MAIOR_IGUAL_40_DOSE_PARA_TEOR_ALTO DOUBLE PRECISION,
            ADD COLUMN IF NOT EXISTS OBSERVACOES VARCHAR(1000),
            ADD COLUMN IF NOT EXISTS FONTES VARCHAR(1000);

        SELECT COUNT(*) INTO null_count
        FROM TEORES_E_DOSES_DE_K
        WHERE ID_TABELA IS NULL
           OR CTC_MENOR_40_TEOR_BAIXO_MENOR_QUE IS NULL
           OR CTC_MENOR_40_DOSE_PARA_TEOR_BAIXO IS NULL
           OR CTC_MENOR_40_MEDIO_MENOR_TEOR IS NULL
           OR CTC_MENOR_40_MEDIO_MAIOR_TEOR IS NULL
           OR CTC_MENOR_40_DOSE_PARA_TEOR_MEDIO IS NULL
           OR CTC_MENOR_40_ADEQUADO_MENOR_TEOR IS NULL
           OR CTC_MENOR_40_ADEQUADO_MAIOR_TEOR IS NULL
           OR CTC_MENOR_40_DOSE_PARA_TEOR_ADEQUADO IS NULL
           OR CTC_MENOR_40_TEOR_ALTO_MAIOR_QUE IS NULL
           OR CTC_MENOR_40_DOSE_PARA_TEOR_ALTO IS NULL
           OR CTC_MAIOR_IGUAL_40_TEOR_BAIXO_MENOR_QUE IS NULL
           OR CTC_MAIOR_IGUAL_40_DOSE_PARA_TEOR_BAIXO IS NULL
           OR CTC_MAIOR_IGUAL_40_MEDIO_MENOR_TEOR IS NULL
           OR CTC_MAIOR_IGUAL_40_MEDIO_MAIOR_TEOR IS NULL
           OR CTC_MAIOR_IGUAL_40_DOSE_PARA_TEOR_MEDIO IS NULL
           OR CTC_MAIOR_IGUAL_40_ADEQUADO_MENOR_TEOR IS NULL
           OR CTC_MAIOR_IGUAL_40_ADEQUADO_MAIOR_TEOR IS NULL
           OR CTC_MAIOR_IGUAL_40_DOSE_PARA_TEOR_ADEQUADO IS NULL
           OR CTC_MAIOR_IGUAL_40_TEOR_ALTO_MAIOR_QUE IS NULL
           OR CTC_MAIOR_IGUAL_40_DOSE_PARA_TEOR_ALTO IS NULL;

        IF null_count = 0 THEN
            ALTER TABLE TEORES_E_DOSES_DE_K
                ALTER COLUMN ID_TABELA SET NOT NULL,
                ALTER COLUMN CTC_MENOR_40_TEOR_BAIXO_MENOR_QUE SET NOT NULL,
                ALTER COLUMN CTC_MENOR_40_DOSE_PARA_TEOR_BAIXO SET NOT NULL,
                ALTER COLUMN CTC_MENOR_40_MEDIO_MENOR_TEOR SET NOT NULL,
                ALTER COLUMN CTC_MENOR_40_MEDIO_MAIOR_TEOR SET NOT NULL,
                ALTER COLUMN CTC_MENOR_40_DOSE_PARA_TEOR_MEDIO SET NOT NULL,
                ALTER COLUMN CTC_MENOR_40_ADEQUADO_MENOR_TEOR SET NOT NULL,
                ALTER COLUMN CTC_MENOR_40_ADEQUADO_MAIOR_TEOR SET NOT NULL,
                ALTER COLUMN CTC_MENOR_40_DOSE_PARA_TEOR_ADEQUADO SET NOT NULL,
                ALTER COLUMN CTC_MENOR_40_TEOR_ALTO_MAIOR_QUE SET NOT NULL,
                ALTER COLUMN CTC_MENOR_40_DOSE_PARA_TEOR_ALTO SET NOT NULL,
                ALTER COLUMN CTC_MAIOR_IGUAL_40_TEOR_BAIXO_MENOR_QUE SET NOT NULL,
                ALTER COLUMN CTC_MAIOR_IGUAL_40_DOSE_PARA_TEOR_BAIXO SET NOT NULL,
                ALTER COLUMN CTC_MAIOR_IGUAL_40_MEDIO_MENOR_TEOR SET NOT NULL,
                ALTER COLUMN CTC_MAIOR_IGUAL_40_MEDIO_MAIOR_TEOR SET NOT NULL,
                ALTER COLUMN CTC_MAIOR_IGUAL_40_DOSE_PARA_TEOR_MEDIO SET NOT NULL,
                ALTER COLUMN CTC_MAIOR_IGUAL_40_ADEQUADO_MENOR_TEOR SET NOT NULL,
                ALTER COLUMN CTC_MAIOR_IGUAL_40_ADEQUADO_MAIOR_TEOR SET NOT NULL,
                ALTER COLUMN CTC_MAIOR_IGUAL_40_DOSE_PARA_TEOR_ADEQUADO SET NOT NULL,
                ALTER COLUMN CTC_MAIOR_IGUAL_40_TEOR_ALTO_MAIOR_QUE SET NOT NULL,
                ALTER COLUMN CTC_MAIOR_IGUAL_40_DOSE_PARA_TEOR_ALTO SET NOT NULL;
        ELSE
            RAISE NOTICE 'TEORES_E_DOSES_DE_K contem % linha(s) com dados obrigatorios nulos; constraints NOT NULL foram preservadas como nullable para evitar dados agronomicos inventados.', null_count;
        END IF;

        SELECT COUNT(*) INTO duplicate_count
        FROM (
            SELECT ID_TABELA
            FROM TEORES_E_DOSES_DE_K
            WHERE ID_TABELA IS NOT NULL
            GROUP BY ID_TABELA
            HAVING COUNT(*) > 1
        ) duplicated;

        IF duplicate_count = 0
           AND NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'uk_teores_doses_k_id_tabela') THEN
            ALTER TABLE TEORES_E_DOSES_DE_K
                ADD CONSTRAINT UK_TEORES_DOSES_K_ID_TABELA UNIQUE (ID_TABELA);
        ELSIF duplicate_count > 0 THEN
            RAISE NOTICE 'TEORES_E_DOSES_DE_K contem ID_TABELA duplicado; unique constraint nao foi criada.';
        END IF;

        IF parent_exists THEN
            SELECT COUNT(*) INTO orphan_count
            FROM TEORES_E_DOSES_DE_K k
            LEFT JOIN TABELAS_DE_CRITERIOS_DE_INTERPRETACAO_DA_FERTILIDADE_DO_SOLO t ON t.id = k.ID_TABELA
            WHERE k.ID_TABELA IS NOT NULL
              AND t.id IS NULL;

            IF orphan_count = 0
               AND NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_teores_doses_k_tabela') THEN
                ALTER TABLE TEORES_E_DOSES_DE_K
                    ADD CONSTRAINT FK_TEORES_DOSES_K_TABELA
                    FOREIGN KEY (ID_TABELA)
                    REFERENCES TABELAS_DE_CRITERIOS_DE_INTERPRETACAO_DA_FERTILIDADE_DO_SOLO(id);
            ELSIF orphan_count > 0 THEN
                RAISE NOTICE 'TEORES_E_DOSES_DE_K contem % registro(s) sem tabela de criterios correspondente; FK nao foi criada.', orphan_count;
            END IF;
        END IF;
    END IF;
END $$;

DO $$
DECLARE
    table_exists BOOLEAN;
    parent_exists BOOLEAN;
    null_count BIGINT;
    orphan_count BIGINT;
    duplicate_count BIGINT;
BEGIN
    parent_exists := to_regclass('public.tabelas_de_criterios_de_interpretacao_da_fertilidade_do_solo') IS NOT NULL;

    IF parent_exists AND to_regclass('public.teores_fosforo_argila_doses_fosfato') IS NULL THEN
        CREATE TABLE TEORES_FOSFORO_ARGILA_DOSES_FOSFATO (
            id BIGSERIAL PRIMARY KEY,
            ID_TABELA BIGINT NOT NULL,
            SEQUEIRO_MENOR_TEOR_ARGILA DOUBLE PRECISION NOT NULL,
            SEQUEIRO_MENOR_ARGILA_DOSE_P_MUITO_BAIXO DOUBLE PRECISION NOT NULL,
            SEQUEIRO_MENOR_ARGILA_DOSE_P_BAIXO DOUBLE PRECISION NOT NULL,
            SEQUEIRO_MENOR_ARGILA_DOSE_P_MEDIO DOUBLE PRECISION NOT NULL,
            SEQUEIRO_INTERVALO_1_MENOR_TEOR_ARGILA DOUBLE PRECISION NOT NULL,
            SEQUEIRO_INTERVALO_1_MAIOR_TEOR_ARGILA DOUBLE PRECISION NOT NULL,
            SEQUEIRO_INTERVALO_1_DOSE_P_MUITO_BAIXO DOUBLE PRECISION NOT NULL,
            SEQUEIRO_INTERVALO_1_DOSE_P_BAIXO DOUBLE PRECISION NOT NULL,
            SEQUEIRO_INTERVALO_1_DOSE_P_MEDIO DOUBLE PRECISION NOT NULL,
            SEQUEIRO_INTERVALO_2_MENOR_TEOR_ARGILA DOUBLE PRECISION NOT NULL,
            SEQUEIRO_INTERVALO_2_MAIOR_TEOR_ARGILA DOUBLE PRECISION NOT NULL,
            SEQUEIRO_INTERVALO_2_DOSE_P_MUITO_BAIXO DOUBLE PRECISION NOT NULL,
            SEQUEIRO_INTERVALO_2_DOSE_P_BAIXO DOUBLE PRECISION NOT NULL,
            SEQUEIRO_INTERVALO_2_DOSE_P_MEDIO DOUBLE PRECISION NOT NULL,
            SEQUEIRO_MAIOR_TEOR_ARGILA DOUBLE PRECISION NOT NULL,
            SEQUEIRO_MAIOR_ARGILA_DOSE_P_MUITO_BAIXO DOUBLE PRECISION NOT NULL,
            SEQUEIRO_MAIOR_ARGILA_DOSE_P_BAIXO DOUBLE PRECISION NOT NULL,
            SEQUEIRO_MAIOR_ARGILA_DOSE_P_MEDIO DOUBLE PRECISION NOT NULL,
            IRRIGADO_MENOR_TEOR_ARGILA DOUBLE PRECISION NOT NULL,
            IRRIGADO_MENOR_ARGILA_DOSE_P_MUITO_BAIXO DOUBLE PRECISION NOT NULL,
            IRRIGADO_MENOR_ARGILA_DOSE_P_BAIXO DOUBLE PRECISION NOT NULL,
            IRRIGADO_MENOR_ARGILA_DOSE_P_MEDIO DOUBLE PRECISION NOT NULL,
            IRRIGADO_INTERVALO_1_MENOR_TEOR_ARGILA DOUBLE PRECISION NOT NULL,
            IRRIGADO_INTERVALO_1_MAIOR_TEOR_ARGILA DOUBLE PRECISION NOT NULL,
            IRRIGADO_INTERVALO_1_DOSE_P_MUITO_BAIXO DOUBLE PRECISION NOT NULL,
            IRRIGADO_INTERVALO_1_DOSE_P_BAIXO DOUBLE PRECISION NOT NULL,
            IRRIGADO_INTERVALO_1_DOSE_P_MEDIO DOUBLE PRECISION NOT NULL,
            IRRIGADO_INTERVALO_2_MENOR_TEOR_ARGILA DOUBLE PRECISION NOT NULL,
            IRRIGADO_INTERVALO_2_MAIOR_TEOR_ARGILA DOUBLE PRECISION NOT NULL,
            IRRIGADO_INTERVALO_2_DOSE_P_MUITO_BAIXO DOUBLE PRECISION NOT NULL,
            IRRIGADO_INTERVALO_2_DOSE_P_BAIXO DOUBLE PRECISION NOT NULL,
            IRRIGADO_INTERVALO_2_DOSE_P_MEDIO DOUBLE PRECISION NOT NULL,
            IRRIGADO_MAIOR_TEOR_ARGILA DOUBLE PRECISION NOT NULL,
            IRRIGADO_MAIOR_ARGILA_DOSE_P_MUITO_BAIXO DOUBLE PRECISION NOT NULL,
            IRRIGADO_MAIOR_ARGILA_DOSE_P_BAIXO DOUBLE PRECISION NOT NULL,
            IRRIGADO_MAIOR_ARGILA_DOSE_P_MEDIO DOUBLE PRECISION NOT NULL,
            OBSERVACOES VARCHAR(1000),
            FONTES VARCHAR(1000)
        );
    END IF;

    table_exists := to_regclass('public.teores_fosforo_argila_doses_fosfato') IS NOT NULL;
    IF table_exists THEN
        ALTER TABLE TEORES_FOSFORO_ARGILA_DOSES_FOSFATO
            ADD COLUMN IF NOT EXISTS ID_TABELA BIGINT,
            ADD COLUMN IF NOT EXISTS SEQUEIRO_MENOR_TEOR_ARGILA DOUBLE PRECISION,
            ADD COLUMN IF NOT EXISTS SEQUEIRO_MENOR_ARGILA_DOSE_P_MUITO_BAIXO DOUBLE PRECISION,
            ADD COLUMN IF NOT EXISTS SEQUEIRO_MENOR_ARGILA_DOSE_P_BAIXO DOUBLE PRECISION,
            ADD COLUMN IF NOT EXISTS SEQUEIRO_MENOR_ARGILA_DOSE_P_MEDIO DOUBLE PRECISION,
            ADD COLUMN IF NOT EXISTS SEQUEIRO_INTERVALO_1_MENOR_TEOR_ARGILA DOUBLE PRECISION,
            ADD COLUMN IF NOT EXISTS SEQUEIRO_INTERVALO_1_MAIOR_TEOR_ARGILA DOUBLE PRECISION,
            ADD COLUMN IF NOT EXISTS SEQUEIRO_INTERVALO_1_DOSE_P_MUITO_BAIXO DOUBLE PRECISION,
            ADD COLUMN IF NOT EXISTS SEQUEIRO_INTERVALO_1_DOSE_P_BAIXO DOUBLE PRECISION,
            ADD COLUMN IF NOT EXISTS SEQUEIRO_INTERVALO_1_DOSE_P_MEDIO DOUBLE PRECISION,
            ADD COLUMN IF NOT EXISTS SEQUEIRO_INTERVALO_2_MENOR_TEOR_ARGILA DOUBLE PRECISION,
            ADD COLUMN IF NOT EXISTS SEQUEIRO_INTERVALO_2_MAIOR_TEOR_ARGILA DOUBLE PRECISION,
            ADD COLUMN IF NOT EXISTS SEQUEIRO_INTERVALO_2_DOSE_P_MUITO_BAIXO DOUBLE PRECISION,
            ADD COLUMN IF NOT EXISTS SEQUEIRO_INTERVALO_2_DOSE_P_BAIXO DOUBLE PRECISION,
            ADD COLUMN IF NOT EXISTS SEQUEIRO_INTERVALO_2_DOSE_P_MEDIO DOUBLE PRECISION,
            ADD COLUMN IF NOT EXISTS SEQUEIRO_MAIOR_TEOR_ARGILA DOUBLE PRECISION,
            ADD COLUMN IF NOT EXISTS SEQUEIRO_MAIOR_ARGILA_DOSE_P_MUITO_BAIXO DOUBLE PRECISION,
            ADD COLUMN IF NOT EXISTS SEQUEIRO_MAIOR_ARGILA_DOSE_P_BAIXO DOUBLE PRECISION,
            ADD COLUMN IF NOT EXISTS SEQUEIRO_MAIOR_ARGILA_DOSE_P_MEDIO DOUBLE PRECISION,
            ADD COLUMN IF NOT EXISTS IRRIGADO_MENOR_TEOR_ARGILA DOUBLE PRECISION,
            ADD COLUMN IF NOT EXISTS IRRIGADO_MENOR_ARGILA_DOSE_P_MUITO_BAIXO DOUBLE PRECISION,
            ADD COLUMN IF NOT EXISTS IRRIGADO_MENOR_ARGILA_DOSE_P_BAIXO DOUBLE PRECISION,
            ADD COLUMN IF NOT EXISTS IRRIGADO_MENOR_ARGILA_DOSE_P_MEDIO DOUBLE PRECISION,
            ADD COLUMN IF NOT EXISTS IRRIGADO_INTERVALO_1_MENOR_TEOR_ARGILA DOUBLE PRECISION,
            ADD COLUMN IF NOT EXISTS IRRIGADO_INTERVALO_1_MAIOR_TEOR_ARGILA DOUBLE PRECISION,
            ADD COLUMN IF NOT EXISTS IRRIGADO_INTERVALO_1_DOSE_P_MUITO_BAIXO DOUBLE PRECISION,
            ADD COLUMN IF NOT EXISTS IRRIGADO_INTERVALO_1_DOSE_P_BAIXO DOUBLE PRECISION,
            ADD COLUMN IF NOT EXISTS IRRIGADO_INTERVALO_1_DOSE_P_MEDIO DOUBLE PRECISION,
            ADD COLUMN IF NOT EXISTS IRRIGADO_INTERVALO_2_MENOR_TEOR_ARGILA DOUBLE PRECISION,
            ADD COLUMN IF NOT EXISTS IRRIGADO_INTERVALO_2_MAIOR_TEOR_ARGILA DOUBLE PRECISION,
            ADD COLUMN IF NOT EXISTS IRRIGADO_INTERVALO_2_DOSE_P_MUITO_BAIXO DOUBLE PRECISION,
            ADD COLUMN IF NOT EXISTS IRRIGADO_INTERVALO_2_DOSE_P_BAIXO DOUBLE PRECISION,
            ADD COLUMN IF NOT EXISTS IRRIGADO_INTERVALO_2_DOSE_P_MEDIO DOUBLE PRECISION,
            ADD COLUMN IF NOT EXISTS IRRIGADO_MAIOR_TEOR_ARGILA DOUBLE PRECISION,
            ADD COLUMN IF NOT EXISTS IRRIGADO_MAIOR_ARGILA_DOSE_P_MUITO_BAIXO DOUBLE PRECISION,
            ADD COLUMN IF NOT EXISTS IRRIGADO_MAIOR_ARGILA_DOSE_P_BAIXO DOUBLE PRECISION,
            ADD COLUMN IF NOT EXISTS IRRIGADO_MAIOR_ARGILA_DOSE_P_MEDIO DOUBLE PRECISION,
            ADD COLUMN IF NOT EXISTS OBSERVACOES VARCHAR(1000),
            ADD COLUMN IF NOT EXISTS FONTES VARCHAR(1000);

        SELECT COUNT(*) INTO null_count
        FROM TEORES_FOSFORO_ARGILA_DOSES_FOSFATO
        WHERE ID_TABELA IS NULL
           OR SEQUEIRO_MENOR_TEOR_ARGILA IS NULL
           OR SEQUEIRO_MENOR_ARGILA_DOSE_P_MUITO_BAIXO IS NULL
           OR SEQUEIRO_MENOR_ARGILA_DOSE_P_BAIXO IS NULL
           OR SEQUEIRO_MENOR_ARGILA_DOSE_P_MEDIO IS NULL
           OR SEQUEIRO_INTERVALO_1_MENOR_TEOR_ARGILA IS NULL
           OR SEQUEIRO_INTERVALO_1_MAIOR_TEOR_ARGILA IS NULL
           OR SEQUEIRO_INTERVALO_1_DOSE_P_MUITO_BAIXO IS NULL
           OR SEQUEIRO_INTERVALO_1_DOSE_P_BAIXO IS NULL
           OR SEQUEIRO_INTERVALO_1_DOSE_P_MEDIO IS NULL
           OR SEQUEIRO_INTERVALO_2_MENOR_TEOR_ARGILA IS NULL
           OR SEQUEIRO_INTERVALO_2_MAIOR_TEOR_ARGILA IS NULL
           OR SEQUEIRO_INTERVALO_2_DOSE_P_MUITO_BAIXO IS NULL
           OR SEQUEIRO_INTERVALO_2_DOSE_P_BAIXO IS NULL
           OR SEQUEIRO_INTERVALO_2_DOSE_P_MEDIO IS NULL
           OR SEQUEIRO_MAIOR_TEOR_ARGILA IS NULL
           OR SEQUEIRO_MAIOR_ARGILA_DOSE_P_MUITO_BAIXO IS NULL
           OR SEQUEIRO_MAIOR_ARGILA_DOSE_P_BAIXO IS NULL
           OR SEQUEIRO_MAIOR_ARGILA_DOSE_P_MEDIO IS NULL
           OR IRRIGADO_MENOR_TEOR_ARGILA IS NULL
           OR IRRIGADO_MENOR_ARGILA_DOSE_P_MUITO_BAIXO IS NULL
           OR IRRIGADO_MENOR_ARGILA_DOSE_P_BAIXO IS NULL
           OR IRRIGADO_MENOR_ARGILA_DOSE_P_MEDIO IS NULL
           OR IRRIGADO_INTERVALO_1_MENOR_TEOR_ARGILA IS NULL
           OR IRRIGADO_INTERVALO_1_MAIOR_TEOR_ARGILA IS NULL
           OR IRRIGADO_INTERVALO_1_DOSE_P_MUITO_BAIXO IS NULL
           OR IRRIGADO_INTERVALO_1_DOSE_P_BAIXO IS NULL
           OR IRRIGADO_INTERVALO_1_DOSE_P_MEDIO IS NULL
           OR IRRIGADO_INTERVALO_2_MENOR_TEOR_ARGILA IS NULL
           OR IRRIGADO_INTERVALO_2_MAIOR_TEOR_ARGILA IS NULL
           OR IRRIGADO_INTERVALO_2_DOSE_P_MUITO_BAIXO IS NULL
           OR IRRIGADO_INTERVALO_2_DOSE_P_BAIXO IS NULL
           OR IRRIGADO_INTERVALO_2_DOSE_P_MEDIO IS NULL
           OR IRRIGADO_MAIOR_TEOR_ARGILA IS NULL
           OR IRRIGADO_MAIOR_ARGILA_DOSE_P_MUITO_BAIXO IS NULL
           OR IRRIGADO_MAIOR_ARGILA_DOSE_P_BAIXO IS NULL
           OR IRRIGADO_MAIOR_ARGILA_DOSE_P_MEDIO IS NULL;

        IF null_count = 0 THEN
            ALTER TABLE TEORES_FOSFORO_ARGILA_DOSES_FOSFATO
                ALTER COLUMN ID_TABELA SET NOT NULL,
                ALTER COLUMN SEQUEIRO_MENOR_TEOR_ARGILA SET NOT NULL,
                ALTER COLUMN SEQUEIRO_MENOR_ARGILA_DOSE_P_MUITO_BAIXO SET NOT NULL,
                ALTER COLUMN SEQUEIRO_MENOR_ARGILA_DOSE_P_BAIXO SET NOT NULL,
                ALTER COLUMN SEQUEIRO_MENOR_ARGILA_DOSE_P_MEDIO SET NOT NULL,
                ALTER COLUMN SEQUEIRO_INTERVALO_1_MENOR_TEOR_ARGILA SET NOT NULL,
                ALTER COLUMN SEQUEIRO_INTERVALO_1_MAIOR_TEOR_ARGILA SET NOT NULL,
                ALTER COLUMN SEQUEIRO_INTERVALO_1_DOSE_P_MUITO_BAIXO SET NOT NULL,
                ALTER COLUMN SEQUEIRO_INTERVALO_1_DOSE_P_BAIXO SET NOT NULL,
                ALTER COLUMN SEQUEIRO_INTERVALO_1_DOSE_P_MEDIO SET NOT NULL,
                ALTER COLUMN SEQUEIRO_INTERVALO_2_MENOR_TEOR_ARGILA SET NOT NULL,
                ALTER COLUMN SEQUEIRO_INTERVALO_2_MAIOR_TEOR_ARGILA SET NOT NULL,
                ALTER COLUMN SEQUEIRO_INTERVALO_2_DOSE_P_MUITO_BAIXO SET NOT NULL,
                ALTER COLUMN SEQUEIRO_INTERVALO_2_DOSE_P_BAIXO SET NOT NULL,
                ALTER COLUMN SEQUEIRO_INTERVALO_2_DOSE_P_MEDIO SET NOT NULL,
                ALTER COLUMN SEQUEIRO_MAIOR_TEOR_ARGILA SET NOT NULL,
                ALTER COLUMN SEQUEIRO_MAIOR_ARGILA_DOSE_P_MUITO_BAIXO SET NOT NULL,
                ALTER COLUMN SEQUEIRO_MAIOR_ARGILA_DOSE_P_BAIXO SET NOT NULL,
                ALTER COLUMN SEQUEIRO_MAIOR_ARGILA_DOSE_P_MEDIO SET NOT NULL,
                ALTER COLUMN IRRIGADO_MENOR_TEOR_ARGILA SET NOT NULL,
                ALTER COLUMN IRRIGADO_MENOR_ARGILA_DOSE_P_MUITO_BAIXO SET NOT NULL,
                ALTER COLUMN IRRIGADO_MENOR_ARGILA_DOSE_P_BAIXO SET NOT NULL,
                ALTER COLUMN IRRIGADO_MENOR_ARGILA_DOSE_P_MEDIO SET NOT NULL,
                ALTER COLUMN IRRIGADO_INTERVALO_1_MENOR_TEOR_ARGILA SET NOT NULL,
                ALTER COLUMN IRRIGADO_INTERVALO_1_MAIOR_TEOR_ARGILA SET NOT NULL,
                ALTER COLUMN IRRIGADO_INTERVALO_1_DOSE_P_MUITO_BAIXO SET NOT NULL,
                ALTER COLUMN IRRIGADO_INTERVALO_1_DOSE_P_BAIXO SET NOT NULL,
                ALTER COLUMN IRRIGADO_INTERVALO_1_DOSE_P_MEDIO SET NOT NULL,
                ALTER COLUMN IRRIGADO_INTERVALO_2_MENOR_TEOR_ARGILA SET NOT NULL,
                ALTER COLUMN IRRIGADO_INTERVALO_2_MAIOR_TEOR_ARGILA SET NOT NULL,
                ALTER COLUMN IRRIGADO_INTERVALO_2_DOSE_P_MUITO_BAIXO SET NOT NULL,
                ALTER COLUMN IRRIGADO_INTERVALO_2_DOSE_P_BAIXO SET NOT NULL,
                ALTER COLUMN IRRIGADO_INTERVALO_2_DOSE_P_MEDIO SET NOT NULL,
                ALTER COLUMN IRRIGADO_MAIOR_TEOR_ARGILA SET NOT NULL,
                ALTER COLUMN IRRIGADO_MAIOR_ARGILA_DOSE_P_MUITO_BAIXO SET NOT NULL,
                ALTER COLUMN IRRIGADO_MAIOR_ARGILA_DOSE_P_BAIXO SET NOT NULL,
                ALTER COLUMN IRRIGADO_MAIOR_ARGILA_DOSE_P_MEDIO SET NOT NULL;
        ELSE
            RAISE NOTICE 'TEORES_FOSFORO_ARGILA_DOSES_FOSFATO contem % linha(s) com dados obrigatorios nulos; constraints NOT NULL foram preservadas como nullable para evitar dados agronomicos inventados.', null_count;
        END IF;

        SELECT COUNT(*) INTO duplicate_count
        FROM (
            SELECT ID_TABELA
            FROM TEORES_FOSFORO_ARGILA_DOSES_FOSFATO
            WHERE ID_TABELA IS NOT NULL
            GROUP BY ID_TABELA
            HAVING COUNT(*) > 1
        ) duplicated;

        IF duplicate_count = 0
           AND NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'uk_teores_fosforo_argila_doses_fosfato_id_tabela') THEN
            ALTER TABLE TEORES_FOSFORO_ARGILA_DOSES_FOSFATO
                ADD CONSTRAINT UK_TEORES_FOSFORO_ARGILA_DOSES_FOSFATO_ID_TABELA UNIQUE (ID_TABELA);
        ELSIF duplicate_count > 0 THEN
            RAISE NOTICE 'TEORES_FOSFORO_ARGILA_DOSES_FOSFATO contem ID_TABELA duplicado; unique constraint nao foi criada.';
        END IF;

        IF parent_exists THEN
            SELECT COUNT(*) INTO orphan_count
            FROM TEORES_FOSFORO_ARGILA_DOSES_FOSFATO p
            LEFT JOIN TABELAS_DE_CRITERIOS_DE_INTERPRETACAO_DA_FERTILIDADE_DO_SOLO t ON t.id = p.ID_TABELA
            WHERE p.ID_TABELA IS NOT NULL
              AND t.id IS NULL;

            IF orphan_count = 0
               AND NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_teores_fosforo_argila_doses_fosfato_tabela') THEN
                ALTER TABLE TEORES_FOSFORO_ARGILA_DOSES_FOSFATO
                    ADD CONSTRAINT FK_TEORES_FOSFORO_ARGILA_DOSES_FOSFATO_TABELA
                    FOREIGN KEY (ID_TABELA)
                    REFERENCES TABELAS_DE_CRITERIOS_DE_INTERPRETACAO_DA_FERTILIDADE_DO_SOLO(id);
            ELSIF orphan_count > 0 THEN
                RAISE NOTICE 'TEORES_FOSFORO_ARGILA_DOSES_FOSFATO contem % registro(s) sem tabela de criterios correspondente; FK nao foi criada.', orphan_count;
            END IF;
        END IF;
    END IF;
END $$;

DO $$
DECLARE
    parent_exists BOOLEAN;
    null_count BIGINT;
    orphan_count BIGINT;
BEGIN
    parent_exists := to_regclass('public.tabelas_de_criterios_de_interpretacao_da_fertilidade_do_solo') IS NOT NULL;

    IF parent_exists AND to_regclass('public.adubacao_corretiva_de_p2o5') IS NULL THEN
        CREATE TABLE ADUBACAO_CORRETIVA_DE_P2O5 (
            id BIGSERIAL PRIMARY KEY,
            ID_TABELA BIGINT NOT NULL,
            ARGILA_MINIMA DOUBLE PRECISION,
            ARGILA_MAXIMA DOUBLE PRECISION,
            P_MEHLICH_MINIMO DOUBLE PRECISION,
            P_MEHLICH_MAXIMO DOUBLE PRECISION,
            DOSE_P2O5 DOUBLE PRECISION NOT NULL,
            OBSERVACOES VARCHAR(1000),
            FONTES VARCHAR(1000)
        );
    END IF;

    IF to_regclass('public.adubacao_corretiva_de_p2o5') IS NOT NULL THEN
        ALTER TABLE ADUBACAO_CORRETIVA_DE_P2O5
            ADD COLUMN IF NOT EXISTS ID_TABELA BIGINT,
            ADD COLUMN IF NOT EXISTS ARGILA_MINIMA DOUBLE PRECISION,
            ADD COLUMN IF NOT EXISTS ARGILA_MAXIMA DOUBLE PRECISION,
            ADD COLUMN IF NOT EXISTS P_MEHLICH_MINIMO DOUBLE PRECISION,
            ADD COLUMN IF NOT EXISTS P_MEHLICH_MAXIMO DOUBLE PRECISION,
            ADD COLUMN IF NOT EXISTS DOSE_P2O5 DOUBLE PRECISION,
            ADD COLUMN IF NOT EXISTS OBSERVACOES VARCHAR(1000),
            ADD COLUMN IF NOT EXISTS FONTES VARCHAR(1000);

        SELECT COUNT(*) INTO null_count
        FROM ADUBACAO_CORRETIVA_DE_P2O5
        WHERE ID_TABELA IS NULL
           OR DOSE_P2O5 IS NULL;

        IF null_count = 0 THEN
            ALTER TABLE ADUBACAO_CORRETIVA_DE_P2O5
                ALTER COLUMN ID_TABELA SET NOT NULL,
                ALTER COLUMN DOSE_P2O5 SET NOT NULL;
        ELSE
            RAISE NOTICE 'ADUBACAO_CORRETIVA_DE_P2O5 contem % linha(s) com ID_TABELA/DOSE_P2O5 nulos; NOT NULL nao foi aplicado.', null_count;
        END IF;

        CREATE INDEX IF NOT EXISTS IDX_ADUBACAO_CORRETIVA_P2O5_TABELA
            ON ADUBACAO_CORRETIVA_DE_P2O5 (ID_TABELA);

        IF parent_exists THEN
            SELECT COUNT(*) INTO orphan_count
            FROM ADUBACAO_CORRETIVA_DE_P2O5 c
            LEFT JOIN TABELAS_DE_CRITERIOS_DE_INTERPRETACAO_DA_FERTILIDADE_DO_SOLO t ON t.id = c.ID_TABELA
            WHERE c.ID_TABELA IS NOT NULL
              AND t.id IS NULL;

            IF orphan_count = 0
               AND NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_adubacao_corretiva_p2o5_tabela') THEN
                ALTER TABLE ADUBACAO_CORRETIVA_DE_P2O5
                    ADD CONSTRAINT FK_ADUBACAO_CORRETIVA_P2O5_TABELA
                    FOREIGN KEY (ID_TABELA)
                    REFERENCES TABELAS_DE_CRITERIOS_DE_INTERPRETACAO_DA_FERTILIDADE_DO_SOLO(id);
            ELSIF orphan_count > 0 THEN
                RAISE NOTICE 'ADUBACAO_CORRETIVA_DE_P2O5 contem % registro(s) sem tabela de criterios correspondente; FK nao foi criada.', orphan_count;
            END IF;
        END IF;
    END IF;

    IF parent_exists AND to_regclass('public.adubacao_corretiva_de_k2o') IS NULL THEN
        CREATE TABLE ADUBACAO_CORRETIVA_DE_K2O (
            id BIGSERIAL PRIMARY KEY,
            ID_TABELA BIGINT NOT NULL,
            CTC_MINIMA DOUBLE PRECISION,
            CTC_MAXIMA DOUBLE PRECISION,
            K_MINIMO DOUBLE PRECISION,
            K_MAXIMO DOUBLE PRECISION,
            DOSE_K2O DOUBLE PRECISION NOT NULL,
            OBSERVACOES VARCHAR(1000),
            FONTES VARCHAR(1000)
        );
    END IF;

    IF to_regclass('public.adubacao_corretiva_de_k2o') IS NOT NULL THEN
        ALTER TABLE ADUBACAO_CORRETIVA_DE_K2O
            ADD COLUMN IF NOT EXISTS ID_TABELA BIGINT,
            ADD COLUMN IF NOT EXISTS CTC_MINIMA DOUBLE PRECISION,
            ADD COLUMN IF NOT EXISTS CTC_MAXIMA DOUBLE PRECISION,
            ADD COLUMN IF NOT EXISTS K_MINIMO DOUBLE PRECISION,
            ADD COLUMN IF NOT EXISTS K_MAXIMO DOUBLE PRECISION,
            ADD COLUMN IF NOT EXISTS DOSE_K2O DOUBLE PRECISION,
            ADD COLUMN IF NOT EXISTS OBSERVACOES VARCHAR(1000),
            ADD COLUMN IF NOT EXISTS FONTES VARCHAR(1000);

        SELECT COUNT(*) INTO null_count
        FROM ADUBACAO_CORRETIVA_DE_K2O
        WHERE ID_TABELA IS NULL
           OR DOSE_K2O IS NULL;

        IF null_count = 0 THEN
            ALTER TABLE ADUBACAO_CORRETIVA_DE_K2O
                ALTER COLUMN ID_TABELA SET NOT NULL,
                ALTER COLUMN DOSE_K2O SET NOT NULL;
        ELSE
            RAISE NOTICE 'ADUBACAO_CORRETIVA_DE_K2O contem % linha(s) com ID_TABELA/DOSE_K2O nulos; NOT NULL nao foi aplicado.', null_count;
        END IF;

        CREATE INDEX IF NOT EXISTS IDX_ADUBACAO_CORRETIVA_K2O_TABELA
            ON ADUBACAO_CORRETIVA_DE_K2O (ID_TABELA);

        IF parent_exists THEN
            SELECT COUNT(*) INTO orphan_count
            FROM ADUBACAO_CORRETIVA_DE_K2O c
            LEFT JOIN TABELAS_DE_CRITERIOS_DE_INTERPRETACAO_DA_FERTILIDADE_DO_SOLO t ON t.id = c.ID_TABELA
            WHERE c.ID_TABELA IS NOT NULL
              AND t.id IS NULL;

            IF orphan_count = 0
               AND NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_adubacao_corretiva_k2o_tabela') THEN
                ALTER TABLE ADUBACAO_CORRETIVA_DE_K2O
                    ADD CONSTRAINT FK_ADUBACAO_CORRETIVA_K2O_TABELA
                    FOREIGN KEY (ID_TABELA)
                    REFERENCES TABELAS_DE_CRITERIOS_DE_INTERPRETACAO_DA_FERTILIDADE_DO_SOLO(id);
            ELSIF orphan_count > 0 THEN
                RAISE NOTICE 'ADUBACAO_CORRETIVA_DE_K2O contem % registro(s) sem tabela de criterios correspondente; FK nao foi criada.', orphan_count;
            END IF;
        END IF;
    END IF;
END $$;

ALTER TABLE IF EXISTS LINHAS_MICRONUTRIENTES_RECOMENDACAO_DIRETA
    DROP COLUMN IF EXISTS FERTILIZER_NAME,
    DROP COLUMN IF EXISTS MICRONUTRIENT_CONCENTRATION_PERCENT;

ALTER TABLE IF EXISTS LINHAS_ADUBACAO_PLANTIO_RECOMENDACAO_DIRETA
    DROP COLUMN IF EXISTS FERTILIZER_NAME,
    DROP COLUMN IF EXISTS N_PERCENT,
    DROP COLUMN IF EXISTS P2O5_PERCENT,
    DROP COLUMN IF EXISTS K2O_PERCENT;

ALTER TABLE IF EXISTS LINHAS_ADUBACAO_COBERTURA_RECOMENDACAO_DIRETA
    DROP COLUMN IF EXISTS FERTILIZER_NAME,
    DROP COLUMN IF EXISTS N_PERCENT,
    DROP COLUMN IF EXISTS P2O5_PERCENT,
    DROP COLUMN IF EXISTS K2O_PERCENT;
