ALTER TABLE LINHAS_ADUBACAO_PLANTIO_RECOMENDACAO_DIRETA
    ADD COLUMN IF NOT EXISTS RECOMMENDED_OPTION BOOLEAN,
    ADD COLUMN IF NOT EXISTS OPTION_TOTAL_COST DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS PRICE_OBSERVATION VARCHAR(1000);

ALTER TABLE LINHAS_ADUBACAO_COBERTURA_RECOMENDACAO_DIRETA
    ADD COLUMN IF NOT EXISTS RECOMMENDED_OPTION BOOLEAN,
    ADD COLUMN IF NOT EXISTS OPTION_TOTAL_COST DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS PRICE_OBSERVATION VARCHAR(1000);
