CREATE TABLE IF NOT EXISTS DOSES_CORRETIVAS_FOSFORO (
    id BIGSERIAL PRIMARY KEY,
    ID_TABELA BIGINT NOT NULL,
    FAIXA_TEXTO VARCHAR(100),
    TEOR_INICIAL DOUBLE PRECISION,
    TEOR_FINAL DOUBLE PRECISION,
    DOSE_P2O5_KG_HA DOUBLE PRECISION NOT NULL,
    OBSERVACOES VARCHAR(1000),
    FONTES VARCHAR(1000),
    CONSTRAINT FK_DOSES_CORRETIVAS_FOSFORO_TABELA FOREIGN KEY (ID_TABELA)
        REFERENCES TABELAS_DE_CRITERIOS_DE_INTERPRETACAO_DA_FERTILIDADE_DO_SOLO(id)
);

CREATE INDEX IF NOT EXISTS IDX_DOSES_CORRETIVAS_FOSFORO_TABELA
    ON DOSES_CORRETIVAS_FOSFORO (ID_TABELA);

CREATE INDEX IF NOT EXISTS IDX_DOSES_CORRETIVAS_FOSFORO_FAIXA
    ON DOSES_CORRETIVAS_FOSFORO (ID_TABELA, TEOR_INICIAL, TEOR_FINAL);

CREATE TABLE IF NOT EXISTS DOSES_CORRETIVAS_POTASSIO (
    id BIGSERIAL PRIMARY KEY,
    ID_TABELA BIGINT NOT NULL,
    FAIXA_TEXTO VARCHAR(100),
    TEOR_INICIAL DOUBLE PRECISION,
    TEOR_FINAL DOUBLE PRECISION,
    DOSE_K2O_KG_HA DOUBLE PRECISION NOT NULL,
    OBSERVACOES VARCHAR(1000),
    FONTES VARCHAR(1000),
    CONSTRAINT FK_DOSES_CORRETIVAS_POTASSIO_TABELA FOREIGN KEY (ID_TABELA)
        REFERENCES TABELAS_DE_CRITERIOS_DE_INTERPRETACAO_DA_FERTILIDADE_DO_SOLO(id)
);

CREATE INDEX IF NOT EXISTS IDX_DOSES_CORRETIVAS_POTASSIO_TABELA
    ON DOSES_CORRETIVAS_POTASSIO (ID_TABELA);

CREATE INDEX IF NOT EXISTS IDX_DOSES_CORRETIVAS_POTASSIO_FAIXA
    ON DOSES_CORRETIVAS_POTASSIO (ID_TABELA, TEOR_INICIAL, TEOR_FINAL);
