CREATE TABLE IF NOT EXISTS DOSES_DE_ENXOFRE (
    id BIGSERIAL PRIMARY KEY,
    ID_TABELA BIGINT NOT NULL,
    MUITO_BAIXO_DOSE_ARGILA_MENOR_400 DOUBLE PRECISION NOT NULL,
    BAIXO_DOSE_ARGILA_MENOR_400 DOUBLE PRECISION NOT NULL,
    MEDIO_DOSE_ARGILA_MENOR_400 DOUBLE PRECISION NOT NULL,
    ALTO_DOSE_ARGILA_MENOR_400 DOUBLE PRECISION NOT NULL,
    MUITO_ALTO_DOSE_ARGILA_MENOR_400 DOUBLE PRECISION NOT NULL,
    MUITO_BAIXO_DOSE_ARGILA_MAIOR_400 DOUBLE PRECISION NOT NULL,
    BAIXO_DOSE_ARGILA_MAIOR_400 DOUBLE PRECISION NOT NULL,
    MEDIO_DOSE_ARGILA_MAIOR_400 DOUBLE PRECISION NOT NULL,
    ALTO_DOSE_ARGILA_MAIOR_400 DOUBLE PRECISION NOT NULL,
    MUITO_ALTO_DOSE_ARGILA_MAIOR_400 DOUBLE PRECISION NOT NULL,
    OBSERVACOES VARCHAR(1000),
    FONTES VARCHAR(1000),
    CONSTRAINT UK_DOSES_DE_ENXOFRE_ID_TABELA UNIQUE (ID_TABELA),
    CONSTRAINT FK_DOSES_DE_ENXOFRE_TABELA FOREIGN KEY (ID_TABELA)
        REFERENCES TABELAS_DE_CRITERIOS_DE_INTERPRETACAO_DA_FERTILIDADE_DO_SOLO(id)
);
