ALTER TABLE PROPRIEDADES ADD COLUMN IF NOT EXISTS LATITUDE_GRAUS INTEGER;
ALTER TABLE PROPRIEDADES ADD COLUMN IF NOT EXISTS LATITUDE_MINUTOS INTEGER;
ALTER TABLE PROPRIEDADES ADD COLUMN IF NOT EXISTS LATITUDE_SEGUNDOS DOUBLE PRECISION;
ALTER TABLE PROPRIEDADES ADD COLUMN IF NOT EXISTS LONGITUDE_GRAUS INTEGER;
ALTER TABLE PROPRIEDADES ADD COLUMN IF NOT EXISTS LONGITUDE_MINUTOS INTEGER;
ALTER TABLE PROPRIEDADES ADD COLUMN IF NOT EXISTS LONGITUDE_SEGUNDOS DOUBLE PRECISION;

ALTER TABLE TALHOES ADD COLUMN IF NOT EXISTS LATITUDE_GRAUS INTEGER;
ALTER TABLE TALHOES ADD COLUMN IF NOT EXISTS LATITUDE_MINUTOS INTEGER;
ALTER TABLE TALHOES ADD COLUMN IF NOT EXISTS LATITUDE_SEGUNDOS DOUBLE PRECISION;
ALTER TABLE TALHOES ADD COLUMN IF NOT EXISTS LONGITUDE_GRAUS INTEGER;
ALTER TABLE TALHOES ADD COLUMN IF NOT EXISTS LONGITUDE_MINUTOS INTEGER;
ALTER TABLE TALHOES ADD COLUMN IF NOT EXISTS LONGITUDE_SEGUNDOS DOUBLE PRECISION;
