ALTER TABLE ADUBOS_MINERAIS_SIMPLES
    ADD COLUMN IF NOT EXISTS OBSERVACAO TEXT,
    ADD COLUMN IF NOT EXISTS FONTE TEXT;

ALTER TABLE ADUBOS_MINERAIS_FORMULADOS
    ADD COLUMN IF NOT EXISTS OBSERVACAO TEXT,
    ADD COLUMN IF NOT EXISTS FONTE TEXT;

ALTER TABLE ADUBOS_ORGANO_MINERAIS
    ADD COLUMN IF NOT EXISTS OBSERVACAO TEXT,
    ADD COLUMN IF NOT EXISTS FONTE TEXT;

ALTER TABLE ADUBOS_ORGANICOS
    ADD COLUMN IF NOT EXISTS OBSERVACAO TEXT,
    ADD COLUMN IF NOT EXISTS FONTE TEXT;

ALTER TABLE ADUBOS_VERDES
    ADD COLUMN IF NOT EXISTS OBSERVACAO TEXT,
    ADD COLUMN IF NOT EXISTS FONTE TEXT;

ALTER TABLE ADUBOS_MINERAIS
    ADD COLUMN IF NOT EXISTS OBSERVACAO TEXT,
    ADD COLUMN IF NOT EXISTS FONTE TEXT;

ALTER TABLE ADUBOS_QUELATADOS
    ADD COLUMN IF NOT EXISTS OBSERVACAO TEXT,
    ADD COLUMN IF NOT EXISTS FONTE TEXT;

ALTER TABLE BIO_FERTILIZANTES
    ADD COLUMN IF NOT EXISTS OBSERVACAO TEXT,
    ADD COLUMN IF NOT EXISTS FONTE TEXT;
