ALTER TABLE EXTRATOS_ANALISES_FISICAS
    ADD COLUMN IF NOT EXISTS UNIDADE_TEOR_DE_AREIA VARCHAR(20) NOT NULL DEFAULT 'g/dm3',
    ADD COLUMN IF NOT EXISTS UNIDADE_TEOR_DE_SILTE VARCHAR(20) NOT NULL DEFAULT 'g/dm3',
    ADD COLUMN IF NOT EXISTS UNIDADE_TEOR_DE_ARGILA VARCHAR(20) NOT NULL DEFAULT 'g/dm3',
    ADD COLUMN IF NOT EXISTS UNIDADE_DENSIDADE_APARENTE VARCHAR(20) NOT NULL DEFAULT 'g/dm3',
    ADD COLUMN IF NOT EXISTS UNIDADE_DENSIDADE_REAL VARCHAR(20) NOT NULL DEFAULT 'g/dm3';

UPDATE EXTRATOS_ANALISES_FISICAS
SET UNIDADE_TEOR_DE_AREIA = 'g/dm3'
WHERE UNIDADE_TEOR_DE_AREIA IS NULL
   OR LOWER(REPLACE(UNIDADE_TEOR_DE_AREIA, '³', '3')) IN ('g/kg', 'g_per_kg');

UPDATE EXTRATOS_ANALISES_FISICAS
SET UNIDADE_TEOR_DE_SILTE = 'g/dm3'
WHERE UNIDADE_TEOR_DE_SILTE IS NULL
   OR LOWER(REPLACE(UNIDADE_TEOR_DE_SILTE, '³', '3')) IN ('g/kg', 'g_per_kg');

UPDATE EXTRATOS_ANALISES_FISICAS
SET UNIDADE_TEOR_DE_ARGILA = 'g/dm3'
WHERE UNIDADE_TEOR_DE_ARGILA IS NULL
   OR LOWER(REPLACE(UNIDADE_TEOR_DE_ARGILA, '³', '3')) IN ('g/kg', 'g_per_kg');

UPDATE EXTRATOS_ANALISES_FISICAS
SET UNIDADE_DENSIDADE_APARENTE = 'g/dm3'
WHERE UNIDADE_DENSIDADE_APARENTE IS NULL
   OR LOWER(REPLACE(UNIDADE_DENSIDADE_APARENTE, '³', '3')) IN ('g/kg', 'g_per_kg');

UPDATE EXTRATOS_ANALISES_FISICAS
SET UNIDADE_DENSIDADE_REAL = 'g/dm3'
WHERE UNIDADE_DENSIDADE_REAL IS NULL
   OR LOWER(REPLACE(UNIDADE_DENSIDADE_REAL, '³', '3')) IN ('g/kg', 'g_per_kg');
