DO $$
BEGIN
    IF to_regclass('public.extratos_analises_fisicas') IS NOT NULL THEN
        ALTER TABLE EXTRATOS_ANALISES_FISICAS
            ADD COLUMN IF NOT EXISTS UNIDADE_TEOR_DE_AREIA VARCHAR(20),
            ADD COLUMN IF NOT EXISTS UNIDADE_TEOR_DE_SILTE VARCHAR(20),
            ADD COLUMN IF NOT EXISTS UNIDADE_TEOR_DE_ARGILA VARCHAR(20);

        ALTER TABLE EXTRATOS_ANALISES_FISICAS
            ALTER COLUMN UNIDADE_TEOR_DE_AREIA SET DEFAULT 'g/kg',
            ALTER COLUMN UNIDADE_TEOR_DE_SILTE SET DEFAULT 'g/kg',
            ALTER COLUMN UNIDADE_TEOR_DE_ARGILA SET DEFAULT 'g/kg';

        UPDATE EXTRATOS_ANALISES_FISICAS
        SET UNIDADE_TEOR_DE_AREIA = 'g/kg'
        WHERE UNIDADE_TEOR_DE_AREIA IS NULL
           OR LOWER(REPLACE(UNIDADE_TEOR_DE_AREIA, '³', '3')) IN ('g/dm3', 'g_per_dm3', 'g/kg', 'g_per_kg');

        UPDATE EXTRATOS_ANALISES_FISICAS
        SET UNIDADE_TEOR_DE_SILTE = 'g/kg'
        WHERE UNIDADE_TEOR_DE_SILTE IS NULL
           OR LOWER(REPLACE(UNIDADE_TEOR_DE_SILTE, '³', '3')) IN ('g/dm3', 'g_per_dm3', 'g/kg', 'g_per_kg');

        UPDATE EXTRATOS_ANALISES_FISICAS
        SET UNIDADE_TEOR_DE_ARGILA = 'g/kg'
        WHERE UNIDADE_TEOR_DE_ARGILA IS NULL
           OR LOWER(REPLACE(UNIDADE_TEOR_DE_ARGILA, '³', '3')) IN ('g/dm3', 'g_per_dm3', 'g/kg', 'g_per_kg');

        ALTER TABLE EXTRATOS_ANALISES_FISICAS
            ALTER COLUMN UNIDADE_TEOR_DE_AREIA SET NOT NULL,
            ALTER COLUMN UNIDADE_TEOR_DE_SILTE SET NOT NULL,
            ALTER COLUMN UNIDADE_TEOR_DE_ARGILA SET NOT NULL;
    END IF;
END $$;
