ALTER TABLE ADUBOS_MINERAIS_SIMPLES
    ADD COLUMN IF NOT EXISTS PRECO_UNIDADE_COMERCIAL DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS UNIDADE_COMERCIAL VARCHAR(100),
    ADD COLUMN IF NOT EXISTS PESO_UNIDADE_COMERCIAL_KG DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS DATA_PRECO DATE;

ALTER TABLE ADUBOS_MINERAIS_FORMULADOS
    ADD COLUMN IF NOT EXISTS PRECO_UNIDADE_COMERCIAL DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS UNIDADE_COMERCIAL VARCHAR(100),
    ADD COLUMN IF NOT EXISTS PESO_UNIDADE_COMERCIAL_KG DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS DATA_PRECO DATE;

ALTER TABLE ADUBOS_ORGANO_MINERAIS
    ADD COLUMN IF NOT EXISTS PRECO_UNIDADE_COMERCIAL DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS UNIDADE_COMERCIAL VARCHAR(100),
    ADD COLUMN IF NOT EXISTS PESO_UNIDADE_COMERCIAL_KG DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS DATA_PRECO DATE;

ALTER TABLE ADUBOS_ORGANICOS
    ADD COLUMN IF NOT EXISTS PRECO_UNIDADE_COMERCIAL DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS UNIDADE_COMERCIAL VARCHAR(100),
    ADD COLUMN IF NOT EXISTS PESO_UNIDADE_COMERCIAL_KG DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS DATA_PRECO DATE;

ALTER TABLE ADUBOS_VERDES
    ADD COLUMN IF NOT EXISTS PRECO_UNIDADE_COMERCIAL DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS UNIDADE_COMERCIAL VARCHAR(100),
    ADD COLUMN IF NOT EXISTS PESO_UNIDADE_COMERCIAL_KG DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS DATA_PRECO DATE;

ALTER TABLE ADUBOS_MINERAIS
    ADD COLUMN IF NOT EXISTS PRECO_UNIDADE_COMERCIAL DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS UNIDADE_COMERCIAL VARCHAR(100),
    ADD COLUMN IF NOT EXISTS PESO_UNIDADE_COMERCIAL_KG DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS DATA_PRECO DATE;

ALTER TABLE ADUBOS_QUELATADOS
    ADD COLUMN IF NOT EXISTS PRECO_UNIDADE_COMERCIAL DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS UNIDADE_COMERCIAL VARCHAR(100),
    ADD COLUMN IF NOT EXISTS PESO_UNIDADE_COMERCIAL_KG DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS DATA_PRECO DATE;

ALTER TABLE BIO_FERTILIZANTES
    ADD COLUMN IF NOT EXISTS PRECO_UNIDADE_COMERCIAL DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS UNIDADE_COMERCIAL VARCHAR(100),
    ADD COLUMN IF NOT EXISTS PESO_UNIDADE_COMERCIAL_KG DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS DATA_PRECO DATE;
