-- Garante compatibilidade entre o modelo relacional de doses de micronutrientes
-- e a coluna legada obrigatória de sugestão textual na tabela principal.
ALTER TABLE TABELAS_ADUBACAO_CULTURAS
    ADD COLUMN IF NOT EXISTS SUGESTAO_DE_ADUBACAO_COM_MICRONUTRIENTES VARCHAR(1000);

DO $$
BEGIN
    IF EXISTS (
        SELECT 1
        FROM information_schema.columns
        WHERE table_name = 'tabelas_adubacao_culturas'
          AND column_name = 'sugestao_de_adubacao_com_micronutrientes'
          AND data_type NOT IN ('character varying', 'text')
    ) THEN
        ALTER TABLE TABELAS_ADUBACAO_CULTURAS
            ALTER COLUMN SUGESTAO_DE_ADUBACAO_COM_MICRONUTRIENTES DROP DEFAULT,
            ALTER COLUMN SUGESTAO_DE_ADUBACAO_COM_MICRONUTRIENTES TYPE VARCHAR(1000)
                USING COALESCE(SUGESTAO_DE_ADUBACAO_COM_MICRONUTRIENTES::text, '');
    END IF;
END $$;

UPDATE TABELAS_ADUBACAO_CULTURAS t
SET SUGESTAO_DE_ADUBACAO_COM_MICRONUTRIENTES = COALESCE((
    SELECT string_agg(d.MICRONUTRIENTE || ': ' || d.DOSE_MINIMA || ' a ' || d.DOSE_MAXIMA, '; ' ORDER BY d.MICRONUTRIENTE)
    FROM DOSES_MICRONUTRIENTES_TABELAS_ADUBACAO_CULTURAS d
    WHERE d.ID_TABELA_ADUBACAO_CULTURA = t.id
), '')
WHERE SUGESTAO_DE_ADUBACAO_COM_MICRONUTRIENTES IS NULL;

ALTER TABLE TABELAS_ADUBACAO_CULTURAS
    ALTER COLUMN SUGESTAO_DE_ADUBACAO_COM_MICRONUTRIENTES SET DEFAULT '',
    ALTER COLUMN SUGESTAO_DE_ADUBACAO_COM_MICRONUTRIENTES SET NOT NULL;
