ALTER TABLE IF EXISTS fosforo_disponivel_com_extrator_resina_troca_anionica
    ADD COLUMN IF NOT EXISTS unidade VARCHAR(20) NOT NULL DEFAULT 'g/dm3',
    ADD COLUMN IF NOT EXISTS muito_baixo DOUBLE PRECISION NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS baixo_menor DOUBLE PRECISION NOT NULL DEFAULT 5,
    ADD COLUMN IF NOT EXISTS baixo_maior DOUBLE PRECISION NOT NULL DEFAULT 10,
    ADD COLUMN IF NOT EXISTS medio_menor DOUBLE PRECISION NOT NULL DEFAULT 10,
    ADD COLUMN IF NOT EXISTS medio_maior DOUBLE PRECISION NOT NULL DEFAULT 20,
    ADD COLUMN IF NOT EXISTS alto_menor DOUBLE PRECISION NOT NULL DEFAULT 20,
    ADD COLUMN IF NOT EXISTS alto_maior DOUBLE PRECISION NOT NULL DEFAULT 999,
    ADD COLUMN IF NOT EXISTS muito_alto DOUBLE PRECISION NOT NULL DEFAULT 999;
