ALTER TABLE ADUBOS_VERDES
    ADD COLUMN IF NOT EXISTS PORCENTAGEM_UMIDADE_INCORPORACAO DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS TAXA_MINERALIZACAO_QUARTO_ANO_PERCENTUAL DOUBLE PRECISION;

ALTER TABLE ADUBOS_ORGANICOS
    ADD COLUMN IF NOT EXISTS TAXA_MINERALIZACAO_QUARTO_ANO_PERCENTUAL DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS ARSENIO_MG_KG DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS CADMIO_MG_KG DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS CROMIO_MG_KG DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS CHUMBO_MG_KG DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS MERCURIO_MG_KG DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS NIQUEL_MG_KG DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS SELENIO_MG_KG DOUBLE PRECISION;

ALTER TABLE ADUBOS_ORGANO_MINERAIS
    ADD COLUMN IF NOT EXISTS TAXA_MINERALIZACAO_PRIMEIRO_ANO_PERCENTUAL DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS TAXA_MINERALIZACAO_SEGUNDO_ANO_PERCENTUAL DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS TAXA_MINERALIZACAO_TERCEIRO_ANO_PERCENTUAL DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS TAXA_MINERALIZACAO_QUARTO_ANO_PERCENTUAL DOUBLE PRECISION;
