ALTER TABLE INTERVALO_TEOR_NUTRIENTE
    ADD COLUMN IF NOT EXISTS UNIDADE_TEOR VARCHAR(20),
    ADD COLUMN IF NOT EXISTS UNIDADE_APLICACAO_PLANTIO VARCHAR(20) NOT NULL DEFAULT 'kg/ha';

ALTER TABLE COBERTURA
    ADD COLUMN IF NOT EXISTS UNIDADE_APLICACAO_COBERTURA VARCHAR(20) NOT NULL DEFAULT 'kg/ha';

ALTER TABLE ADUBACAO_COBERTURA
    ADD COLUMN IF NOT EXISTS UNIDADE_DOSE VARCHAR(20) NOT NULL DEFAULT 'kg/ha';

UPDATE INTERVALO_TEOR_NUTRIENTE
SET UNIDADE_TEOR = 'mg/dm³'
WHERE NUTRIENTE = 1
  AND (UNIDADE_TEOR IS NULL OR LOWER(REPLACE(UNIDADE_TEOR, '³', '3')) IN ('mg/dm3', 'mg_per_dm3', 'mg/dm³'));

UPDATE INTERVALO_TEOR_NUTRIENTE
SET UNIDADE_TEOR = 'mmolc/dm³'
WHERE NUTRIENTE = 2
  AND (
      UNIDADE_TEOR IS NULL
      OR LOWER(REPLACE(UNIDADE_TEOR, '³', '3')) IN ('cmolc/dm3', 'cmolc_per_dm3', 'mmolc/dm3', 'mmolc_per_dm3')
  );

UPDATE INTERVALO_TEOR_NUTRIENTE
SET UNIDADE_TEOR = NULL
WHERE NUTRIENTE = 0;

UPDATE INTERVALO_TEOR_NUTRIENTE
SET UNIDADE_APLICACAO_PLANTIO = 'kg/ha'
WHERE UNIDADE_APLICACAO_PLANTIO IS NULL
   OR LOWER(UNIDADE_APLICACAO_PLANTIO) IN ('kg/ha', 'kg_per_ha', 'kg per ha');

UPDATE COBERTURA
SET UNIDADE_APLICACAO_COBERTURA = 'kg/ha'
WHERE UNIDADE_APLICACAO_COBERTURA IS NULL
   OR LOWER(UNIDADE_APLICACAO_COBERTURA) IN ('kg/ha', 'kg_per_ha', 'kg per ha');

UPDATE ADUBACAO_COBERTURA
SET UNIDADE_DOSE = 'kg/ha'
WHERE UNIDADE_DOSE IS NULL
   OR LOWER(UNIDADE_DOSE) IN ('kg/ha', 'kg_per_ha', 'kg per ha');
