CREATE TABLE IF NOT EXISTS DOSES_DE_MICRONUTRIENTES (
    id BIGSERIAL PRIMARY KEY,
    ID_TABELA BIGINT NOT NULL,
    BORO_BAIXO_DOSE DOUBLE PRECISION,
    BORO_MEDIO_DOSE DOUBLE PRECISION,
    BORO_ALTO_DOSE DOUBLE PRECISION,
    COBRE_BAIXO_DOSE DOUBLE PRECISION,
    COBRE_MEDIO_DOSE DOUBLE PRECISION,
    COBRE_ALTO_DOSE DOUBLE PRECISION,
    FERRO_BAIXO_DOSE DOUBLE PRECISION,
    FERRO_MEDIO_DOSE DOUBLE PRECISION,
    FERRO_ALTO_DOSE DOUBLE PRECISION,
    MANGANES_BAIXO_DOSE DOUBLE PRECISION,
    MANGANES_MEDIO_DOSE DOUBLE PRECISION,
    MANGANES_ALTO_DOSE DOUBLE PRECISION,
    ZINCO_BAIXO_DOSE DOUBLE PRECISION,
    ZINCO_MEDIO_DOSE DOUBLE PRECISION,
    ZINCO_ALTO_DOSE DOUBLE PRECISION,
    OBSERVACOES VARCHAR(1000),
    FONTES VARCHAR(1000),
    CONSTRAINT UK_DOSES_DE_MICRONUTRIENTES_ID_TABELA UNIQUE (ID_TABELA),
    CONSTRAINT FK_DOSES_DE_MICRONUTRIENTES_TABELA FOREIGN KEY (ID_TABELA)
        REFERENCES TABELAS_DE_CRITERIOS_DE_INTERPRETACAO_DA_FERTILIDADE_DO_SOLO(id)
);
