UPDATE EXTRATOS_ANALISES_FERTILIDADE
SET PST = ROUND(((100.0 * COALESCE(SODIO, 0.0) / CTC_PH_7)::numeric), 1)::double precision
WHERE CTC_PH_7 IS NOT NULL
  AND CTC_PH_7 <> 0.0;

UPDATE EXTRATOS_ANALISES_FERTILIDADE
SET PST = NULL
WHERE CTC_PH_7 IS NULL
   OR CTC_PH_7 = 0.0;
