CREATE TABLE IF NOT EXISTS SODIO_TROCAVEL (
    ID BIGSERIAL PRIMARY KEY,
    ID_TABELA BIGINT NOT NULL UNIQUE,
    CTCLESSTHAN4_3_VERYLOWLESSTHAN DOUBLE PRECISION,
    CTCLESSTHAN4_3_LOWMIN DOUBLE PRECISION,
    CTCLESSTHAN4_3_LOWMAX DOUBLE PRECISION,
    CTCLESSTHAN4_3_MEDIUMMIN DOUBLE PRECISION,
    CTCLESSTHAN4_3_MEDIUMMAX DOUBLE PRECISION,
    CTCLESSTHAN4_3_HIGHMIN DOUBLE PRECISION,
    CTCLESSTHAN4_3_HIGHMAX DOUBLE PRECISION,
    CTCLESSTHAN4_3_VERYHIGHGREATERTHAN DOUBLE PRECISION,
    CTCFROM4_3TO8_6_VERYLOWLESSTHAN DOUBLE PRECISION,
    CTCFROM4_3TO8_6_LOWMIN DOUBLE PRECISION,
    CTCFROM4_3TO8_6_LOWMAX DOUBLE PRECISION,
    CTCFROM4_3TO8_6_MEDIUMMIN DOUBLE PRECISION,
    CTCFROM4_3TO8_6_MEDIUMMAX DOUBLE PRECISION,
    CTCFROM4_3TO8_6_HIGHMIN DOUBLE PRECISION,
    CTCFROM4_3TO8_6_HIGHMAX DOUBLE PRECISION,
    CTCFROM4_3TO8_6_VERYHIGHGREATERTHAN DOUBLE PRECISION,
    CTCFROM8_7TO15_0_VERYLOWLESSTHAN DOUBLE PRECISION,
    CTCFROM8_7TO15_0_LOWMIN DOUBLE PRECISION,
    CTCFROM8_7TO15_0_LOWMAX DOUBLE PRECISION,
    CTCFROM8_7TO15_0_MEDIUMMIN DOUBLE PRECISION,
    CTCFROM8_7TO15_0_MEDIUMMAX DOUBLE PRECISION,
    CTCFROM8_7TO15_0_HIGHMIN DOUBLE PRECISION,
    CTCFROM8_7TO15_0_HIGHMAX DOUBLE PRECISION,
    CTCFROM8_7TO15_0_VERYHIGHGREATERTHAN DOUBLE PRECISION,
    CTCGREATERTHAN15_VERYLOWLESSTHAN DOUBLE PRECISION,
    CTCGREATERTHAN15_LOWMIN DOUBLE PRECISION,
    CTCGREATERTHAN15_LOWMAX DOUBLE PRECISION,
    CTCGREATERTHAN15_MEDIUMMIN DOUBLE PRECISION,
    CTCGREATERTHAN15_MEDIUMMAX DOUBLE PRECISION,
    CTCGREATERTHAN15_HIGHMIN DOUBLE PRECISION,
    CTCGREATERTHAN15_HIGHMAX DOUBLE PRECISION,
    CTCGREATERTHAN15_VERYHIGHGREATERTHAN DOUBLE PRECISION,
    CONSTRAINT FK_SODIO_TROCAVEL_TABELA FOREIGN KEY (ID_TABELA)
        REFERENCES TABELAS_DE_CRITERIOS_DE_INTERPRETACAO_DA_FERTILIDADE_DO_SOLO(ID) ON DELETE CASCADE
);

INSERT INTO SODIO_TROCAVEL (
    ID_TABELA,
    CTCLESSTHAN4_3_VERYLOWLESSTHAN, CTCLESSTHAN4_3_LOWMIN, CTCLESSTHAN4_3_LOWMAX,
    CTCLESSTHAN4_3_MEDIUMMIN, CTCLESSTHAN4_3_MEDIUMMAX, CTCLESSTHAN4_3_HIGHMIN,
    CTCLESSTHAN4_3_HIGHMAX, CTCLESSTHAN4_3_VERYHIGHGREATERTHAN
)
SELECT ID_TABELA, MENOR_TEOR_SODIO, TEOR_INICIAL_BAIXO_SODIO, TEOR_FINAL_BAIXO_SODIO,
       TEOR_INICIAL_MEDIO_SODIO, TEOR_FINAL_MEDIO_SODIO, TEOR_INICIAL_ALTO_SODIO,
       TEOR_FINAL_ALTO_SODIO, MAIOR_TEOR_SODIO
FROM FAIXAS_DE_TEORES_DIVERSOS
WHERE MENOR_TEOR_SODIO IS NOT NULL
ON CONFLICT (ID_TABELA) DO NOTHING;

ALTER TABLE IF EXISTS FAIXAS_DE_TEORES_DIVERSOS
    DROP COLUMN IF EXISTS MENOR_TEOR_SODIO,
    DROP COLUMN IF EXISTS TEOR_INICIAL_BAIXO_SODIO,
    DROP COLUMN IF EXISTS TEOR_FINAL_BAIXO_SODIO,
    DROP COLUMN IF EXISTS TEOR_INICIAL_MEDIO_SODIO,
    DROP COLUMN IF EXISTS TEOR_FINAL_MEDIO_SODIO,
    DROP COLUMN IF EXISTS TEOR_INICIAL_ALTO_SODIO,
    DROP COLUMN IF EXISTS TEOR_FINAL_ALTO_SODIO,
    DROP COLUMN IF EXISTS MAIOR_TEOR_SODIO;
