ALTER TABLE IF EXISTS ENXOFRE_DISPONIVEL_NO_SOLO
    ADD COLUMN IF NOT EXISTS FONTES VARCHAR(1000);

UPDATE ENXOFRE_DISPONIVEL_NO_SOLO
SET FONTES = FONTE_LITERATURA
WHERE FONTES IS NULL
  AND FONTE_LITERATURA IS NOT NULL;
