UPDATE LINHAS_TABELAS_DE_INTERPRETACAO_DE_ANÁLISE_FOLIAR_DE_CULTURAS
SET N_UNIDADE_TEORES = 'g_per_kg'
WHERE N_UNIDADE_TEORES = 'dag_per_kg';

UPDATE LINHAS_TABELAS_DE_INTERPRETACAO_DE_ANÁLISE_FOLIAR_DE_CULTURAS
SET P_UNIDADE_TEORES = 'g_per_kg'
WHERE P_UNIDADE_TEORES = 'dag_per_kg';

UPDATE LINHAS_TABELAS_DE_INTERPRETACAO_DE_ANÁLISE_FOLIAR_DE_CULTURAS
SET K_UNIDADE_TEORES = 'g_per_kg'
WHERE K_UNIDADE_TEORES = 'dag_per_kg';

UPDATE LINHAS_TABELAS_DE_INTERPRETACAO_DE_ANÁLISE_FOLIAR_DE_CULTURAS
SET Ca_UNIDADE_TEORES = 'g_per_kg'
WHERE Ca_UNIDADE_TEORES = 'dag_per_kg';

UPDATE LINHAS_TABELAS_DE_INTERPRETACAO_DE_ANÁLISE_FOLIAR_DE_CULTURAS
SET MG_UNIDADE_TEORES = 'g_per_kg'
WHERE MG_UNIDADE_TEORES = 'dag_per_kg';

UPDATE LINHAS_TABELAS_DE_INTERPRETACAO_DE_ANÁLISE_FOLIAR_DE_CULTURAS
SET S_UNIDADE_TEORES = 'g_per_kg'
WHERE S_UNIDADE_TEORES = 'dag_per_kg';
