ALTER TABLE BIO_FERTILIZANTES ADD COLUMN IF NOT EXISTS DENSIDADE_G_ML DOUBLE PRECISION;
ALTER TABLE BIO_FERTILIZANTES ADD COLUMN IF NOT EXISTS CONCENTRACAO_VOLUME_G_L DOUBLE PRECISION;
ALTER TABLE BIO_FERTILIZANTES ADD COLUMN IF NOT EXISTS CONCENTRACAO_MASSA_G_KG DOUBLE PRECISION;
ALTER TABLE BIO_FERTILIZANTES ADD COLUMN IF NOT EXISTS PROTEINAS_G_L DOUBLE PRECISION;
ALTER TABLE BIO_FERTILIZANTES ADD COLUMN IF NOT EXISTS AMINOACIDOS_G_L DOUBLE PRECISION;
ALTER TABLE BIO_FERTILIZANTES ADD COLUMN IF NOT EXISTS AMIDOS_G_L DOUBLE PRECISION;
ALTER TABLE BIO_FERTILIZANTES ADD COLUMN IF NOT EXISTS ACUCARES_G_L DOUBLE PRECISION;
ALTER TABLE BIO_FERTILIZANTES ADD COLUMN IF NOT EXISTS COMPOSTOS_DIVERSOS_G_L DOUBLE PRECISION;
