ALTER TABLE TABELAS_ADUBACAO_CULTURAS
    ALTER COLUMN OBSERVACOES TYPE VARCHAR(1000);

ALTER TABLE TABELAS_ADUBACAO_CULTURAS
    ALTER COLUMN FONTES TYPE VARCHAR(1000);

ALTER TABLE TABELAS_DE_INTERPRETACAO_DE_ANÁLISE_FOLIAR_DE_CULTURAS
    ALTER COLUMN OBSERVACOES TYPE VARCHAR(1000);

ALTER TABLE TABELAS_DE_INTERPRETACAO_DE_ANÁLISE_FOLIAR_DE_CULTURAS
    ALTER COLUMN FONTES TYPE VARCHAR(1000);

ALTER TABLE TABELAS_DE_CRITERIOS_DE_INTERPRETACAO_DA_FERTILIDADE_DO_SOLO
    ALTER COLUMN OBSERVACOES TYPE VARCHAR(1000);

ALTER TABLE TABELAS_DE_CRITERIOS_DE_INTERPRETACAO_DA_FERTILIDADE_DO_SOLO
    ALTER COLUMN FONTES TYPE VARCHAR(1000);

ALTER TABLE ENXOFRE_DISPONIVEL_NO_SOLO
    ALTER COLUMN FONTE_LITERATURA TYPE VARCHAR(1000);
