ALTER TABLE LINHAS_MICRONUTRIENTES_RECOMENDACAO_DIRETA
    DROP COLUMN IF EXISTS FERTILIZER_NAME,
    DROP COLUMN IF EXISTS MICRONUTRIENT_CONCENTRATION_PERCENT;

ALTER TABLE LINHAS_ADUBACAO_PLANTIO_RECOMENDACAO_DIRETA
    DROP COLUMN IF EXISTS FERTILIZER_NAME,
    DROP COLUMN IF EXISTS N_PERCENT,
    DROP COLUMN IF EXISTS P2O5_PERCENT,
    DROP COLUMN IF EXISTS K2O_PERCENT;

ALTER TABLE LINHAS_ADUBACAO_COBERTURA_RECOMENDACAO_DIRETA
    DROP COLUMN IF EXISTS FERTILIZER_NAME,
    DROP COLUMN IF EXISTS N_PERCENT,
    DROP COLUMN IF EXISTS P2O5_PERCENT,
    DROP COLUMN IF EXISTS K2O_PERCENT;
